<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/rpc/status.proto

namespace GPBMetadata\Google\Rpc;

class Status
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Any::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0af8010a17676f6f676c652f7270632f7374617475732e70726f746f120a" .
            "676f6f676c652e7270631a19676f6f676c652f70726f746f6275662f616e" .
            "792e70726f746f224e0a06537461747573120c0a04636f64651801200128" .
            "05120f0a076d65737361676518022001280912250a0764657461696c7318" .
            "032003280b32142e676f6f676c652e70726f746f6275662e416e79425e0a" .
            "0e636f6d2e676f6f676c652e727063420b53746174757350726f746f5001" .
            "5a37676f6f676c652e676f6c616e672e6f72672f67656e70726f746f2f67" .
            "6f6f676c65617069732f7270632f7374617475733b737461747573a20203" .
            "525043620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

