<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/iam/admin/v1/iam.proto

namespace Google\Iam\Admin\V1;

/**
 * <pre>
 * `KeyType` filters to selectively retrieve certain varieties
 * of keys.
 * </pre>
 *
 * Protobuf enum <code>google.iam.admin.v1.ListServiceAccountKeysRequest.KeyType</code>
 */
class ListServiceAccountKeysRequest_KeyType
{
    /**
     * <pre>
     * Unspecified key type. The presence of this in the
     * message will immediately result in an error.
     * </pre>
     *
     * <code>KEY_TYPE_UNSPECIFIED = 0;</code>
     */
    const KEY_TYPE_UNSPECIFIED = 0;
    /**
     * <pre>
     * User-managed keys (managed and rotated by the user).
     * </pre>
     *
     * <code>USER_MANAGED = 1;</code>
     */
    const USER_MANAGED = 1;
    /**
     * <pre>
     * System-managed keys (managed and rotated by Google).
     * </pre>
     *
     * <code>SYSTEM_MANAGED = 2;</code>
     */
    const SYSTEM_MANAGED = 2;
}

