<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/iam/admin/v1/iam.proto

namespace Google\Iam\Admin\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * The service account keys list request.
 * </pre>
 *
 * Protobuf type <code>google.iam.admin.v1.ListServiceAccountKeysRequest</code>
 */
class ListServiceAccountKeysRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The resource name of the service account in the following format:
     * `projects/{project}/serviceAccounts/{account}`.
     * Using `-` as a wildcard for the project, will infer the project from
     * the account. The `account` value can be the `email` address or the
     * `unique_id` of the service account.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    private $name = '';
    /**
     * <pre>
     * Filters the types of keys the user wants to include in the list
     * response. Duplicate key types are not allowed. If no key type
     * is provided, all keys are returned.
     * </pre>
     *
     * <code>repeated .google.iam.admin.v1.ListServiceAccountKeysRequest.KeyType key_types = 2;</code>
     */
    private $key_types;

    public function __construct() {
        \GPBMetadata\Google\Iam\Admin\V1\Iam::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The resource name of the service account in the following format:
     * `projects/{project}/serviceAccounts/{account}`.
     * Using `-` as a wildcard for the project, will infer the project from
     * the account. The `account` value can be the `email` address or the
     * `unique_id` of the service account.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * <pre>
     * The resource name of the service account in the following format:
     * `projects/{project}/serviceAccounts/{account}`.
     * Using `-` as a wildcard for the project, will infer the project from
     * the account. The `account` value can be the `email` address or the
     * `unique_id` of the service account.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

    /**
     * <pre>
     * Filters the types of keys the user wants to include in the list
     * response. Duplicate key types are not allowed. If no key type
     * is provided, all keys are returned.
     * </pre>
     *
     * <code>repeated .google.iam.admin.v1.ListServiceAccountKeysRequest.KeyType key_types = 2;</code>
     */
    public function getKeyTypes()
    {
        return $this->key_types;
    }

    /**
     * <pre>
     * Filters the types of keys the user wants to include in the list
     * response. Duplicate key types are not allowed. If no key type
     * is provided, all keys are returned.
     * </pre>
     *
     * <code>repeated .google.iam.admin.v1.ListServiceAccountKeysRequest.KeyType key_types = 2;</code>
     */
    public function setKeyTypes(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, Google\Iam\Admin\V1\ListServiceAccountKeysRequest_KeyType::class);
        $this->key_types = $var;
    }

}

