<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/iam/admin/v1/iam.proto

namespace Google\Iam\Admin\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * The service account list response.
 * </pre>
 *
 * Protobuf type <code>google.iam.admin.v1.ListServiceAccountsResponse</code>
 */
class ListServiceAccountsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The list of matching service accounts.
     * </pre>
     *
     * <code>repeated .google.iam.admin.v1.ServiceAccount accounts = 1;</code>
     */
    private $accounts;
    /**
     * <pre>
     * To retrieve the next page of results, set
     * [ListServiceAccountsRequest.page_token][google.iam.admin.v1.ListServiceAccountsRequest.page_token]
     * to this value.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     */
    private $next_page_token = '';

    public function __construct() {
        \GPBMetadata\Google\Iam\Admin\V1\Iam::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The list of matching service accounts.
     * </pre>
     *
     * <code>repeated .google.iam.admin.v1.ServiceAccount accounts = 1;</code>
     */
    public function getAccounts()
    {
        return $this->accounts;
    }

    /**
     * <pre>
     * The list of matching service accounts.
     * </pre>
     *
     * <code>repeated .google.iam.admin.v1.ServiceAccount accounts = 1;</code>
     */
    public function setAccounts(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Iam\Admin\V1\ServiceAccount::class);
        $this->accounts = $arr;
    }

    /**
     * <pre>
     * To retrieve the next page of results, set
     * [ListServiceAccountsRequest.page_token][google.iam.admin.v1.ListServiceAccountsRequest.page_token]
     * to this value.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     */
    public function getNextPageToken()
    {
        return $this->next_page_token;
    }

    /**
     * <pre>
     * To retrieve the next page of results, set
     * [ListServiceAccountsRequest.page_token][google.iam.admin.v1.ListServiceAccountsRequest.page_token]
     * to this value.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     */
    public function setNextPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->next_page_token = $var;
    }

}

