<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/iam/admin/v1/iam.proto

namespace Google\Iam\Admin\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * The service account keys list response.
 * </pre>
 *
 * Protobuf type <code>google.iam.admin.v1.ListServiceAccountKeysResponse</code>
 */
class ListServiceAccountKeysResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The public keys for the service account.
     * </pre>
     *
     * <code>repeated .google.iam.admin.v1.ServiceAccountKey keys = 1;</code>
     */
    private $keys;

    public function __construct() {
        \GPBMetadata\Google\Iam\Admin\V1\Iam::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The public keys for the service account.
     * </pre>
     *
     * <code>repeated .google.iam.admin.v1.ServiceAccountKey keys = 1;</code>
     */
    public function getKeys()
    {
        return $this->keys;
    }

    /**
     * <pre>
     * The public keys for the service account.
     * </pre>
     *
     * <code>repeated .google.iam.admin.v1.ServiceAccountKey keys = 1;</code>
     */
    public function setKeys(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Iam\Admin\V1\ServiceAccountKey::class);
        $this->keys = $arr;
    }

}

