<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/iam/admin/v1/iam.proto

namespace Google\Iam\Admin\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Represents a service account key.
 * A service account has two sets of key-pairs: user-managed, and
 * system-managed.
 * User-managed key-pairs can be created and deleted by users.  Users are
 * responsible for rotating these keys periodically to ensure security of
 * their service accounts.  Users retain the private key of these key-pairs,
 * and Google retains ONLY the public key.
 * System-managed key-pairs are managed automatically by Google, and rotated
 * daily without user intervention.  The private key never leaves Google's
 * servers to maximize security.
 * Public keys for all service accounts are also published at the OAuth2
 * Service Account API.
 * </pre>
 *
 * Protobuf type <code>google.iam.admin.v1.ServiceAccountKey</code>
 */
class ServiceAccountKey extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The resource name of the service account key in the following format
     * `projects/{project}/serviceAccounts/{account}/keys/{key}`.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    private $name = '';
    /**
     * <pre>
     * The output format for the private key.
     * Only provided in `CreateServiceAccountKey` responses, not
     * in `GetServiceAccountKey` or `ListServiceAccountKey` responses.
     * Google never exposes system-managed private keys, and never retains
     * user-managed private keys.
     * </pre>
     *
     * <code>.google.iam.admin.v1.ServiceAccountPrivateKeyType private_key_type = 2;</code>
     */
    private $private_key_type = 0;
    /**
     * <pre>
     * Specifies the algorithm (and possibly key size) for the key.
     * </pre>
     *
     * <code>.google.iam.admin.v1.ServiceAccountKeyAlgorithm key_algorithm = 8;</code>
     */
    private $key_algorithm = 0;
    /**
     * <pre>
     * The private key data. Only provided in `CreateServiceAccountKey`
     * responses.
     * </pre>
     *
     * <code>bytes private_key_data = 3;</code>
     */
    private $private_key_data = '';
    /**
     * <pre>
     * The public key data. Only provided in `GetServiceAccountKey` responses.
     * </pre>
     *
     * <code>bytes public_key_data = 7;</code>
     */
    private $public_key_data = '';
    /**
     * <pre>
     * The key can be used after this timestamp.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp valid_after_time = 4;</code>
     */
    private $valid_after_time = null;
    /**
     * <pre>
     * The key can be used before this timestamp.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp valid_before_time = 5;</code>
     */
    private $valid_before_time = null;

    public function __construct() {
        \GPBMetadata\Google\Iam\Admin\V1\Iam::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The resource name of the service account key in the following format
     * `projects/{project}/serviceAccounts/{account}/keys/{key}`.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * <pre>
     * The resource name of the service account key in the following format
     * `projects/{project}/serviceAccounts/{account}/keys/{key}`.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

    /**
     * <pre>
     * The output format for the private key.
     * Only provided in `CreateServiceAccountKey` responses, not
     * in `GetServiceAccountKey` or `ListServiceAccountKey` responses.
     * Google never exposes system-managed private keys, and never retains
     * user-managed private keys.
     * </pre>
     *
     * <code>.google.iam.admin.v1.ServiceAccountPrivateKeyType private_key_type = 2;</code>
     */
    public function getPrivateKeyType()
    {
        return $this->private_key_type;
    }

    /**
     * <pre>
     * The output format for the private key.
     * Only provided in `CreateServiceAccountKey` responses, not
     * in `GetServiceAccountKey` or `ListServiceAccountKey` responses.
     * Google never exposes system-managed private keys, and never retains
     * user-managed private keys.
     * </pre>
     *
     * <code>.google.iam.admin.v1.ServiceAccountPrivateKeyType private_key_type = 2;</code>
     */
    public function setPrivateKeyType($var)
    {
        GPBUtil::checkEnum($var, \Google\Iam\Admin\V1\ServiceAccountPrivateKeyType::class);
        $this->private_key_type = $var;
    }

    /**
     * <pre>
     * Specifies the algorithm (and possibly key size) for the key.
     * </pre>
     *
     * <code>.google.iam.admin.v1.ServiceAccountKeyAlgorithm key_algorithm = 8;</code>
     */
    public function getKeyAlgorithm()
    {
        return $this->key_algorithm;
    }

    /**
     * <pre>
     * Specifies the algorithm (and possibly key size) for the key.
     * </pre>
     *
     * <code>.google.iam.admin.v1.ServiceAccountKeyAlgorithm key_algorithm = 8;</code>
     */
    public function setKeyAlgorithm($var)
    {
        GPBUtil::checkEnum($var, \Google\Iam\Admin\V1\ServiceAccountKeyAlgorithm::class);
        $this->key_algorithm = $var;
    }

    /**
     * <pre>
     * The private key data. Only provided in `CreateServiceAccountKey`
     * responses.
     * </pre>
     *
     * <code>bytes private_key_data = 3;</code>
     */
    public function getPrivateKeyData()
    {
        return $this->private_key_data;
    }

    /**
     * <pre>
     * The private key data. Only provided in `CreateServiceAccountKey`
     * responses.
     * </pre>
     *
     * <code>bytes private_key_data = 3;</code>
     */
    public function setPrivateKeyData($var)
    {
        GPBUtil::checkString($var, False);
        $this->private_key_data = $var;
    }

    /**
     * <pre>
     * The public key data. Only provided in `GetServiceAccountKey` responses.
     * </pre>
     *
     * <code>bytes public_key_data = 7;</code>
     */
    public function getPublicKeyData()
    {
        return $this->public_key_data;
    }

    /**
     * <pre>
     * The public key data. Only provided in `GetServiceAccountKey` responses.
     * </pre>
     *
     * <code>bytes public_key_data = 7;</code>
     */
    public function setPublicKeyData($var)
    {
        GPBUtil::checkString($var, False);
        $this->public_key_data = $var;
    }

    /**
     * <pre>
     * The key can be used after this timestamp.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp valid_after_time = 4;</code>
     */
    public function getValidAfterTime()
    {
        return $this->valid_after_time;
    }

    /**
     * <pre>
     * The key can be used after this timestamp.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp valid_after_time = 4;</code>
     */
    public function setValidAfterTime(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->valid_after_time = $var;
    }

    /**
     * <pre>
     * The key can be used before this timestamp.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp valid_before_time = 5;</code>
     */
    public function getValidBeforeTime()
    {
        return $this->valid_before_time;
    }

    /**
     * <pre>
     * The key can be used before this timestamp.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp valid_before_time = 5;</code>
     */
    public function setValidBeforeTime(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->valid_before_time = $var;
    }

}

