<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/iam/admin/v1/iam.proto

namespace Google\Iam\Admin\V1;

/**
 * <pre>
 * Supported public key output formats.
 * </pre>
 *
 * Protobuf enum <code>google.iam.admin.v1.ServiceAccountPublicKeyType</code>
 */
class ServiceAccountPublicKeyType
{
    /**
     * <pre>
     * Unspecified. Returns nothing here.
     * </pre>
     *
     * <code>TYPE_NONE = 0;</code>
     */
    const TYPE_NONE = 0;
    /**
     * <pre>
     * X509 PEM format.
     * </pre>
     *
     * <code>TYPE_X509_PEM_FILE = 1;</code>
     */
    const TYPE_X509_PEM_FILE = 1;
    /**
     * <pre>
     * Raw public key.
     * </pre>
     *
     * <code>TYPE_RAW_PUBLIC_KEY = 2;</code>
     */
    const TYPE_RAW_PUBLIC_KEY = 2;
}

