<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/iam/admin/v1/iam.proto

namespace Google\Iam\Admin\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * The service account sign blob response.
 * </pre>
 *
 * Protobuf type <code>google.iam.admin.v1.SignBlobResponse</code>
 */
class SignBlobResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The id of the key used to sign the blob.
     * </pre>
     *
     * <code>string key_id = 1;</code>
     */
    private $key_id = '';
    /**
     * <pre>
     * The signed blob.
     * </pre>
     *
     * <code>bytes signature = 2;</code>
     */
    private $signature = '';

    public function __construct() {
        \GPBMetadata\Google\Iam\Admin\V1\Iam::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The id of the key used to sign the blob.
     * </pre>
     *
     * <code>string key_id = 1;</code>
     */
    public function getKeyId()
    {
        return $this->key_id;
    }

    /**
     * <pre>
     * The id of the key used to sign the blob.
     * </pre>
     *
     * <code>string key_id = 1;</code>
     */
    public function setKeyId($var)
    {
        GPBUtil::checkString($var, True);
        $this->key_id = $var;
    }

    /**
     * <pre>
     * The signed blob.
     * </pre>
     *
     * <code>bytes signature = 2;</code>
     */
    public function getSignature()
    {
        return $this->signature;
    }

    /**
     * <pre>
     * The signed blob.
     * </pre>
     *
     * <code>bytes signature = 2;</code>
     */
    public function setSignature($var)
    {
        GPBUtil::checkString($var, False);
        $this->signature = $var;
    }

}

