<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/iam/admin/v1/iam.proto

namespace Google\Iam\Admin\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * The service account sign blob request.
 * </pre>
 *
 * Protobuf type <code>google.iam.admin.v1.SignBlobRequest</code>
 */
class SignBlobRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The resource name of the service account in the following format:
     * `projects/{project}/serviceAccounts/{account}`.
     * Using `-` as a wildcard for the project will infer the project from
     * the account. The `account` value can be the `email` address or the
     * `unique_id` of the service account.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    private $name = '';
    /**
     * <pre>
     * The bytes to sign.
     * </pre>
     *
     * <code>bytes bytes_to_sign = 2;</code>
     */
    private $bytes_to_sign = '';

    public function __construct() {
        \GPBMetadata\Google\Iam\Admin\V1\Iam::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The resource name of the service account in the following format:
     * `projects/{project}/serviceAccounts/{account}`.
     * Using `-` as a wildcard for the project will infer the project from
     * the account. The `account` value can be the `email` address or the
     * `unique_id` of the service account.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * <pre>
     * The resource name of the service account in the following format:
     * `projects/{project}/serviceAccounts/{account}`.
     * Using `-` as a wildcard for the project will infer the project from
     * the account. The `account` value can be the `email` address or the
     * `unique_id` of the service account.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

    /**
     * <pre>
     * The bytes to sign.
     * </pre>
     *
     * <code>bytes bytes_to_sign = 2;</code>
     */
    public function getBytesToSign()
    {
        return $this->bytes_to_sign;
    }

    /**
     * <pre>
     * The bytes to sign.
     * </pre>
     *
     * <code>bytes bytes_to_sign = 2;</code>
     */
    public function setBytesToSign($var)
    {
        GPBUtil::checkString($var, False);
        $this->bytes_to_sign = $var;
    }

}

