<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/servicecontrol/v1/check_error.proto

namespace Google\Api\Servicecontrol\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Defines the errors to be returned in
 * [google.api.servicecontrol.v1.CheckResponse.check_errors][google.api.servicecontrol.v1.CheckResponse.check_errors].
 * </pre>
 *
 * Protobuf type <code>google.api.servicecontrol.v1.CheckError</code>
 */
class CheckError extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The error code.
     * </pre>
     *
     * <code>.google.api.servicecontrol.v1.CheckError.Code code = 1;</code>
     */
    private $code = 0;
    /**
     * <pre>
     * Free-form text providing details on the error cause of the error.
     * </pre>
     *
     * <code>string detail = 2;</code>
     */
    private $detail = '';

    public function __construct() {
        \GPBMetadata\Google\Api\Servicecontrol\V1\CheckError::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The error code.
     * </pre>
     *
     * <code>.google.api.servicecontrol.v1.CheckError.Code code = 1;</code>
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * <pre>
     * The error code.
     * </pre>
     *
     * <code>.google.api.servicecontrol.v1.CheckError.Code code = 1;</code>
     */
    public function setCode($var)
    {
        GPBUtil::checkEnum($var, \Google\Api\Servicecontrol\V1\CheckError_Code::class);
        $this->code = $var;
    }

    /**
     * <pre>
     * Free-form text providing details on the error cause of the error.
     * </pre>
     *
     * <code>string detail = 2;</code>
     */
    public function getDetail()
    {
        return $this->detail;
    }

    /**
     * <pre>
     * Free-form text providing details on the error cause of the error.
     * </pre>
     *
     * <code>string detail = 2;</code>
     */
    public function setDetail($var)
    {
        GPBUtil::checkString($var, True);
        $this->detail = $var;
    }

}

