<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/servicecontrol/v1/operation.proto

namespace Google\Api\Servicecontrol\V1;

/**
 * <pre>
 * Defines the importance of the data contained in the operation.
 * </pre>
 *
 * Protobuf enum <code>google.api.servicecontrol.v1.Operation.Importance</code>
 */
class Operation_Importance
{
    /**
     * <pre>
     * The API implementation may cache and aggregate the data.
     * The data may be lost when rare and unexpected system failures occur.
     * </pre>
     *
     * <code>LOW = 0;</code>
     */
    const LOW = 0;
    /**
     * <pre>
     * The API implementation doesn't cache and aggregate the data.
     * If the method returns successfully, it's guaranteed that the data has
     * been persisted in durable storage.
     * </pre>
     *
     * <code>HIGH = 1;</code>
     */
    const HIGH = 1;
}

