<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/servicecontrol/v1/service_controller.proto

namespace Google\Api\Servicecontrol\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Represents the processing error of one `Operation` in the request.
 * </pre>
 *
 * Protobuf type <code>google.api.servicecontrol.v1.ReportResponse.ReportError</code>
 */
class ReportResponse_ReportError extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The [Operation.operation_id][google.api.servicecontrol.v1.Operation.operation_id] value from the request.
     * </pre>
     *
     * <code>string operation_id = 1;</code>
     */
    private $operation_id = '';
    /**
     * <pre>
     * Details of the error when processing the `Operation`.
     * </pre>
     *
     * <code>.google.rpc.Status status = 2;</code>
     */
    private $status = null;

    public function __construct() {
        \GPBMetadata\Google\Api\Servicecontrol\V1\ServiceController::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The [Operation.operation_id][google.api.servicecontrol.v1.Operation.operation_id] value from the request.
     * </pre>
     *
     * <code>string operation_id = 1;</code>
     */
    public function getOperationId()
    {
        return $this->operation_id;
    }

    /**
     * <pre>
     * The [Operation.operation_id][google.api.servicecontrol.v1.Operation.operation_id] value from the request.
     * </pre>
     *
     * <code>string operation_id = 1;</code>
     */
    public function setOperationId($var)
    {
        GPBUtil::checkString($var, True);
        $this->operation_id = $var;
    }

    /**
     * <pre>
     * Details of the error when processing the `Operation`.
     * </pre>
     *
     * <code>.google.rpc.Status status = 2;</code>
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * <pre>
     * Details of the error when processing the `Operation`.
     * </pre>
     *
     * <code>.google.rpc.Status status = 2;</code>
     */
    public function setStatus(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Rpc\Status::class);
        $this->status = $var;
    }

}

