<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/devtools/clouddebugger/v2/data.proto

namespace Google\Devtools\Clouddebugger\V2;

/**
 * <pre>
 * Log severity levels.
 * </pre>
 *
 * Protobuf enum <code>google.devtools.clouddebugger.v2.Breakpoint.LogLevel</code>
 */
class Breakpoint_LogLevel
{
    /**
     * <pre>
     * Information log message.
     * </pre>
     *
     * <code>INFO = 0;</code>
     */
    const INFO = 0;
    /**
     * <pre>
     * Warning log message.
     * </pre>
     *
     * <code>WARNING = 1;</code>
     */
    const WARNING = 1;
    /**
     * <pre>
     * Error log message.
     * </pre>
     *
     * <code>ERROR = 2;</code>
     */
    const ERROR = 2;
}

