<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/devtools/clouddebugger/v2/debugger.proto

namespace Google\Devtools\Clouddebugger\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Response for listing debuggees.
 * </pre>
 *
 * Protobuf type <code>google.devtools.clouddebugger.v2.ListDebuggeesResponse</code>
 */
class ListDebuggeesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * List of debuggees accessible to the calling user.
     * Note that the `description` field is the only human readable field
     * that should be displayed to the user.
     * The fields `debuggee.id` and  `description` fields are guaranteed to be
     * set on each debuggee.
     * </pre>
     *
     * <code>repeated .google.devtools.clouddebugger.v2.Debuggee debuggees = 1;</code>
     */
    private $debuggees;

    public function __construct() {
        \GPBMetadata\Google\Devtools\Clouddebugger\V2\Debugger::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * List of debuggees accessible to the calling user.
     * Note that the `description` field is the only human readable field
     * that should be displayed to the user.
     * The fields `debuggee.id` and  `description` fields are guaranteed to be
     * set on each debuggee.
     * </pre>
     *
     * <code>repeated .google.devtools.clouddebugger.v2.Debuggee debuggees = 1;</code>
     */
    public function getDebuggees()
    {
        return $this->debuggees;
    }

    /**
     * <pre>
     * List of debuggees accessible to the calling user.
     * Note that the `description` field is the only human readable field
     * that should be displayed to the user.
     * The fields `debuggee.id` and  `description` fields are guaranteed to be
     * set on each debuggee.
     * </pre>
     *
     * <code>repeated .google.devtools.clouddebugger.v2.Debuggee debuggees = 1;</code>
     */
    public function setDebuggees(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Devtools\Clouddebugger\V2\Debuggee::class);
        $this->debuggees = $var;
    }

}

