<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/devtools/clouddebugger/v2/controller.proto

namespace Google\Devtools\Clouddebugger\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Response for registering a debuggee.
 * </pre>
 *
 * Protobuf type <code>google.devtools.clouddebugger.v2.RegisterDebuggeeResponse</code>
 */
class RegisterDebuggeeResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * Debuggee resource.
     * The field `id` is guranteed to be set (in addition to the echoed fields).
     * </pre>
     *
     * <code>.google.devtools.clouddebugger.v2.Debuggee debuggee = 1;</code>
     */
    private $debuggee = null;

    public function __construct() {
        \GPBMetadata\Google\Devtools\Clouddebugger\V2\Controller::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Debuggee resource.
     * The field `id` is guranteed to be set (in addition to the echoed fields).
     * </pre>
     *
     * <code>.google.devtools.clouddebugger.v2.Debuggee debuggee = 1;</code>
     */
    public function getDebuggee()
    {
        return $this->debuggee;
    }

    /**
     * <pre>
     * Debuggee resource.
     * The field `id` is guranteed to be set (in addition to the echoed fields).
     * </pre>
     *
     * <code>.google.devtools.clouddebugger.v2.Debuggee debuggee = 1;</code>
     */
    public function setDebuggee(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Devtools\Clouddebugger\V2\Debuggee::class);
        $this->debuggee = $var;
    }

}

