<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/devtools/clouddebugger/v2/debugger.proto

namespace Google\Devtools\Clouddebugger\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Response for setting a breakpoint.
 * </pre>
 *
 * Protobuf type <code>google.devtools.clouddebugger.v2.SetBreakpointResponse</code>
 */
class SetBreakpointResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * Breakpoint resource.
     * The field `id` is guaranteed to be set (in addition to the echoed fileds).
     * </pre>
     *
     * <code>.google.devtools.clouddebugger.v2.Breakpoint breakpoint = 1;</code>
     */
    private $breakpoint = null;

    public function __construct() {
        \GPBMetadata\Google\Devtools\Clouddebugger\V2\Debugger::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Breakpoint resource.
     * The field `id` is guaranteed to be set (in addition to the echoed fileds).
     * </pre>
     *
     * <code>.google.devtools.clouddebugger.v2.Breakpoint breakpoint = 1;</code>
     */
    public function getBreakpoint()
    {
        return $this->breakpoint;
    }

    /**
     * <pre>
     * Breakpoint resource.
     * The field `id` is guaranteed to be set (in addition to the echoed fileds).
     * </pre>
     *
     * <code>.google.devtools.clouddebugger.v2.Breakpoint breakpoint = 1;</code>
     */
    public function setBreakpoint(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Devtools\Clouddebugger\V2\Breakpoint::class);
        $this->breakpoint = $var;
    }

}

