<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/devtools/clouddebugger/v2/debugger.proto

namespace Google\Devtools\Clouddebugger\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Request to set a breakpoint
 * </pre>
 *
 * Protobuf type <code>google.devtools.clouddebugger.v2.SetBreakpointRequest</code>
 */
class SetBreakpointRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * ID of the debuggee where the breakpoint is to be set.
     * </pre>
     *
     * <code>string debuggee_id = 1;</code>
     */
    private $debuggee_id = '';
    /**
     * <pre>
     * Breakpoint specification to set.
     * The field 'location' of the breakpoint must be set.
     * </pre>
     *
     * <code>.google.devtools.clouddebugger.v2.Breakpoint breakpoint = 2;</code>
     */
    private $breakpoint = null;
    /**
     * <pre>
     * The client version making the call.
     * Following: `domain/type/version` (e.g., `google.com/intellij/v1`).
     * </pre>
     *
     * <code>string client_version = 4;</code>
     */
    private $client_version = '';

    public function __construct() {
        \GPBMetadata\Google\Devtools\Clouddebugger\V2\Debugger::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * ID of the debuggee where the breakpoint is to be set.
     * </pre>
     *
     * <code>string debuggee_id = 1;</code>
     */
    public function getDebuggeeId()
    {
        return $this->debuggee_id;
    }

    /**
     * <pre>
     * ID of the debuggee where the breakpoint is to be set.
     * </pre>
     *
     * <code>string debuggee_id = 1;</code>
     */
    public function setDebuggeeId($var)
    {
        GPBUtil::checkString($var, True);
        $this->debuggee_id = $var;
    }

    /**
     * <pre>
     * Breakpoint specification to set.
     * The field 'location' of the breakpoint must be set.
     * </pre>
     *
     * <code>.google.devtools.clouddebugger.v2.Breakpoint breakpoint = 2;</code>
     */
    public function getBreakpoint()
    {
        return $this->breakpoint;
    }

    /**
     * <pre>
     * Breakpoint specification to set.
     * The field 'location' of the breakpoint must be set.
     * </pre>
     *
     * <code>.google.devtools.clouddebugger.v2.Breakpoint breakpoint = 2;</code>
     */
    public function setBreakpoint(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Devtools\Clouddebugger\V2\Breakpoint::class);
        $this->breakpoint = $var;
    }

    /**
     * <pre>
     * The client version making the call.
     * Following: `domain/type/version` (e.g., `google.com/intellij/v1`).
     * </pre>
     *
     * <code>string client_version = 4;</code>
     */
    public function getClientVersion()
    {
        return $this->client_version;
    }

    /**
     * <pre>
     * The client version making the call.
     * Following: `domain/type/version` (e.g., `google.com/intellij/v1`).
     * </pre>
     *
     * <code>string client_version = 4;</code>
     */
    public function setClientVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->client_version = $var;
    }

}

