<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/devtools/clouddebugger/v2/data.proto

namespace Google\Devtools\Clouddebugger\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Represents a location in the source code.
 * </pre>
 *
 * Protobuf type <code>google.devtools.clouddebugger.v2.SourceLocation</code>
 */
class SourceLocation extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * Path to the source file within the source context of the target binary.
     * </pre>
     *
     * <code>string path = 1;</code>
     */
    private $path = '';
    /**
     * <pre>
     * Line inside the file. The first line in the file has the value `1`.
     * </pre>
     *
     * <code>int32 line = 2;</code>
     */
    private $line = 0;

    public function __construct() {
        \GPBMetadata\Google\Devtools\Clouddebugger\V2\Data::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Path to the source file within the source context of the target binary.
     * </pre>
     *
     * <code>string path = 1;</code>
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * <pre>
     * Path to the source file within the source context of the target binary.
     * </pre>
     *
     * <code>string path = 1;</code>
     */
    public function setPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->path = $var;
    }

    /**
     * <pre>
     * Line inside the file. The first line in the file has the value `1`.
     * </pre>
     *
     * <code>int32 line = 2;</code>
     */
    public function getLine()
    {
        return $this->line;
    }

    /**
     * <pre>
     * Line inside the file. The first line in the file has the value `1`.
     * </pre>
     *
     * <code>int32 line = 2;</code>
     */
    public function setLine($var)
    {
        GPBUtil::checkInt32($var);
        $this->line = $var;
    }

}

