<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/devtools/clouddebugger/v2/data.proto

namespace Google\Devtools\Clouddebugger\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Represents a stack frame context.
 * </pre>
 *
 * Protobuf type <code>google.devtools.clouddebugger.v2.StackFrame</code>
 */
class StackFrame extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * Demangled function name at the call site.
     * </pre>
     *
     * <code>string function = 1;</code>
     */
    private $function = '';
    /**
     * <pre>
     * Source location of the call site.
     * </pre>
     *
     * <code>.google.devtools.clouddebugger.v2.SourceLocation location = 2;</code>
     */
    private $location = null;
    /**
     * <pre>
     * Set of arguments passed to this function.
     * Note that this might not be populated for all stack frames.
     * </pre>
     *
     * <code>repeated .google.devtools.clouddebugger.v2.Variable arguments = 3;</code>
     */
    private $arguments;
    /**
     * <pre>
     * Set of local variables at the stack frame location.
     * Note that this might not be populated for all stack frames.
     * </pre>
     *
     * <code>repeated .google.devtools.clouddebugger.v2.Variable locals = 4;</code>
     */
    private $locals;

    public function __construct() {
        \GPBMetadata\Google\Devtools\Clouddebugger\V2\Data::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Demangled function name at the call site.
     * </pre>
     *
     * <code>string function = 1;</code>
     */
    public function getFunction()
    {
        return $this->function;
    }

    /**
     * <pre>
     * Demangled function name at the call site.
     * </pre>
     *
     * <code>string function = 1;</code>
     */
    public function setFunction($var)
    {
        GPBUtil::checkString($var, True);
        $this->function = $var;
    }

    /**
     * <pre>
     * Source location of the call site.
     * </pre>
     *
     * <code>.google.devtools.clouddebugger.v2.SourceLocation location = 2;</code>
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * <pre>
     * Source location of the call site.
     * </pre>
     *
     * <code>.google.devtools.clouddebugger.v2.SourceLocation location = 2;</code>
     */
    public function setLocation(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Devtools\Clouddebugger\V2\SourceLocation::class);
        $this->location = $var;
    }

    /**
     * <pre>
     * Set of arguments passed to this function.
     * Note that this might not be populated for all stack frames.
     * </pre>
     *
     * <code>repeated .google.devtools.clouddebugger.v2.Variable arguments = 3;</code>
     */
    public function getArguments()
    {
        return $this->arguments;
    }

    /**
     * <pre>
     * Set of arguments passed to this function.
     * Note that this might not be populated for all stack frames.
     * </pre>
     *
     * <code>repeated .google.devtools.clouddebugger.v2.Variable arguments = 3;</code>
     */
    public function setArguments(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Devtools\Clouddebugger\V2\Variable::class);
        $this->arguments = $var;
    }

    /**
     * <pre>
     * Set of local variables at the stack frame location.
     * Note that this might not be populated for all stack frames.
     * </pre>
     *
     * <code>repeated .google.devtools.clouddebugger.v2.Variable locals = 4;</code>
     */
    public function getLocals()
    {
        return $this->locals;
    }

    /**
     * <pre>
     * Set of local variables at the stack frame location.
     * Note that this might not be populated for all stack frames.
     * </pre>
     *
     * <code>repeated .google.devtools.clouddebugger.v2.Variable locals = 4;</code>
     */
    public function setLocals(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Devtools\Clouddebugger\V2\Variable::class);
        $this->locals = $var;
    }

}

