<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/devtools/clouddebugger/v2/data.proto

namespace Google\Devtools\Clouddebugger\V2;

/**
 * <pre>
 * Enumerates references to which the message applies.
 * </pre>
 *
 * Protobuf enum <code>google.devtools.clouddebugger.v2.StatusMessage.Reference</code>
 */
class StatusMessage_Reference
{
    /**
     * <pre>
     * Status doesn't refer to any particular input.
     * </pre>
     *
     * <code>UNSPECIFIED = 0;</code>
     */
    const UNSPECIFIED = 0;
    /**
     * <pre>
     * Status applies to the breakpoint and is related to its location.
     * </pre>
     *
     * <code>BREAKPOINT_SOURCE_LOCATION = 3;</code>
     */
    const BREAKPOINT_SOURCE_LOCATION = 3;
    /**
     * <pre>
     * Status applies to the breakpoint and is related to its condition.
     * </pre>
     *
     * <code>BREAKPOINT_CONDITION = 4;</code>
     */
    const BREAKPOINT_CONDITION = 4;
    /**
     * <pre>
     * Status applies to the breakpoint and is related to its expressions.
     * </pre>
     *
     * <code>BREAKPOINT_EXPRESSION = 7;</code>
     */
    const BREAKPOINT_EXPRESSION = 7;
    /**
     * <pre>
     * Status applies to the breakpoint and is related to its age.
     * </pre>
     *
     * <code>BREAKPOINT_AGE = 8;</code>
     */
    const BREAKPOINT_AGE = 8;
    /**
     * <pre>
     * Status applies to the entire variable.
     * </pre>
     *
     * <code>VARIABLE_NAME = 5;</code>
     */
    const VARIABLE_NAME = 5;
    /**
     * <pre>
     * Status applies to variable value (variable name is valid).
     * </pre>
     *
     * <code>VARIABLE_VALUE = 6;</code>
     */
    const VARIABLE_VALUE = 6;
}

