<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: duration.proto

namespace GPBMetadata;

class Duration
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad3010a0e6475726174696f6e2e70726f746f120f676f6f676c652e7072" .
            "6f746f627566222a0a084475726174696f6e120f0a077365636f6e647318" .
            "0120012803120d0a056e616e6f73180220012805427c0a13636f6d2e676f" .
            "6f676c652e70726f746f627566420d4475726174696f6e50726f746f5001" .
            "5a2a6769746875622e636f6d2f676f6c616e672f70726f746f6275662f70" .
            "74797065732f6475726174696f6ef80101a20203475042aa021e476f6f67" .
            "6c652e50726f746f6275662e57656c6c4b6e6f776e547970657362067072" .
            "6f746f33"
        ));

        static::$is_initialized = true;
    }
}

