<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: empty.proto

namespace GPBMetadata;

class GPBEmpty
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa7010a0b656d7074792e70726f746f120f676f6f676c652e70726f746f" .
            "62756622070a05456d70747942760a13636f6d2e676f6f676c652e70726f" .
            "746f627566420a456d70747950726f746f50015a276769746875622e636f" .
            "6d2f676f6c616e672f70726f746f6275662f7074797065732f656d707479" .
            "f80101a20203475042aa021e476f6f676c652e50726f746f6275662e5765" .
            "6c6c4b6e6f776e5479706573620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

