<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/auth.proto

namespace Google\Api;

require_once('google/api/annotations.pb.php');
use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class Authentication extends \Google\Protobuf\Internal\Message
{
    private $rules;
    private $providers;

    public function getRules()
    {
        return $this->rules;
    }

    public function setRules(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Google\Api\AuthenticationRule::class);
        $this->rules = $var;
    }

    public function getProviders()
    {
        return $this->providers;
    }

    public function setProviders(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Google\Api\AuthProvider::class);
        $this->providers = $var;
    }

}

class AuthenticationRule extends \Google\Protobuf\Internal\Message
{
    private $selector = '';
    private $oauth = null;
    private $allow_without_credential = false;
    private $requirements;

    public function getSelector()
    {
        return $this->selector;
    }

    public function setSelector($var)
    {
        GPBUtil::checkString($var, True);
        $this->selector = $var;
    }

    public function getOauth()
    {
        return $this->oauth;
    }

    public function setOauth(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Api\OAuthRequirements::class);
        $this->oauth = $var;
    }

    public function getAllowWithoutCredential()
    {
        return $this->allow_without_credential;
    }

    public function setAllowWithoutCredential($var)
    {
        GPBUtil::checkBool($var);
        $this->allow_without_credential = $var;
    }

    public function getRequirements()
    {
        return $this->requirements;
    }

    public function setRequirements(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Google\Api\AuthRequirement::class);
        $this->requirements = $var;
    }

}

class AuthProvider extends \Google\Protobuf\Internal\Message
{
    private $id = '';
    private $issuer = '';
    private $jwks_uri = '';

    public function getId()
    {
        return $this->id;
    }

    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;
    }

    public function getIssuer()
    {
        return $this->issuer;
    }

    public function setIssuer($var)
    {
        GPBUtil::checkString($var, True);
        $this->issuer = $var;
    }

    public function getJwksUri()
    {
        return $this->jwks_uri;
    }

    public function setJwksUri($var)
    {
        GPBUtil::checkString($var, True);
        $this->jwks_uri = $var;
    }

}

class OAuthRequirements extends \Google\Protobuf\Internal\Message
{
    private $canonical_scopes = '';

    public function getCanonicalScopes()
    {
        return $this->canonical_scopes;
    }

    public function setCanonicalScopes($var)
    {
        GPBUtil::checkString($var, True);
        $this->canonical_scopes = $var;
    }

}

class AuthRequirement extends \Google\Protobuf\Internal\Message
{
    private $provider_id = '';
    private $audiences = '';

    public function getProviderId()
    {
        return $this->provider_id;
    }

    public function setProviderId($var)
    {
        GPBUtil::checkString($var, True);
        $this->provider_id = $var;
    }

    public function getAudiences()
    {
        return $this->audiences;
    }

    public function setAudiences($var)
    {
        GPBUtil::checkString($var, True);
        $this->audiences = $var;
    }

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0ab1040a15676f6f676c652f6170692f617574682e70726f746f120a676f" .
    "6f676c652e6170691a1c676f6f676c652f6170692f616e6e6f746174696f" .
    "6e732e70726f746f226c0a0e41757468656e7469636174696f6e122d0a05" .
    "72756c657318032003280b321e2e676f6f676c652e6170692e4175746865" .
    "6e7469636174696f6e52756c65122b0a0970726f76696465727318042003" .
    "280b32182e676f6f676c652e6170692e4175746850726f766964657222a9" .
    "010a1241757468656e7469636174696f6e52756c6512100a0873656c6563" .
    "746f72180120012809122c0a056f6175746818022001280b321d2e676f6f" .
    "676c652e6170692e4f41757468526571756972656d656e747312200a1861" .
    "6c6c6f775f776974686f75745f63726564656e7469616c18052001280812" .
    "310a0c726571756972656d656e747318072003280b321b2e676f6f676c65" .
    "2e6170692e41757468526571756972656d656e74223c0a0c417574685072" .
    "6f7669646572120a0a026964180120012809120e0a066973737565721802" .
    "2001280912100a086a776b735f757269180320012809222d0a114f417574" .
    "68526571756972656d656e747312180a1063616e6f6e6963616c5f73636f" .
    "70657318012001280922390a0f41757468526571756972656d656e741213" .
    "0a0b70726f76696465725f696418012001280912110a0961756469656e63" .
    "657318022001280942240a0e636f6d2e676f6f676c652e61706942094175" .
    "746850726f746f5001a2020447415049620670726f746f33"
));

