<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/config_change.proto

namespace Google\Api;

use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class ConfigChange extends \Google\Protobuf\Internal\Message
{
    private $element = '';
    private $old_value = '';
    private $new_value = '';
    private $change_type = 0;
    private $advices;

    public function getElement()
    {
        return $this->element;
    }

    public function setElement($var)
    {
        GPBUtil::checkString($var, True);
        $this->element = $var;
    }

    public function getOldValue()
    {
        return $this->old_value;
    }

    public function setOldValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->old_value = $var;
    }

    public function getNewValue()
    {
        return $this->new_value;
    }

    public function setNewValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->new_value = $var;
    }

    public function getChangeType()
    {
        return $this->change_type;
    }

    public function setChangeType($var)
    {
        GPBUtil::checkEnum($var, \Google\Api\ChangeType::class);
        $this->change_type = $var;
    }

    public function getAdvices()
    {
        return $this->advices;
    }

    public function setAdvices(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Google\Api\Advice::class);
        $this->advices = $var;
    }

}

class Advice extends \Google\Protobuf\Internal\Message
{
    private $description = '';

    public function getDescription()
    {
        return $this->description;
    }

    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;
    }

}

class ChangeType
{
    const CHANGE_TYPE_UNSPECIFIED = 0;
    const ADDED = 1;
    const REMOVED = 2;
    const MODIFIED = 3;
}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0aec020a1e676f6f676c652f6170692f636f6e6669675f6368616e67652e" .
    "70726f746f120a676f6f676c652e6170692297010a0c436f6e6669674368" .
    "616e6765120f0a07656c656d656e7418012001280912110a096f6c645f76" .
    "616c756518022001280912110a096e65775f76616c756518032001280912" .
    "2b0a0b6368616e67655f7479706518042001280e32162e676f6f676c652e" .
    "6170692e4368616e67655479706512230a07616476696365731805200328" .
    "0b32122e676f6f676c652e6170692e416476696365221d0a064164766963" .
    "6512130a0b6465736372697074696f6e1802200128092a4f0a0a4368616e" .
    "676554797065121b0a174348414e47455f545950455f554e535045434946" .
    "494544100012090a0541444445441001120b0a0752454d4f564544100212" .
    "0c0a084d4f4449464945441003422c0a0e636f6d2e676f6f676c652e6170" .
    "694211436f6e6669674368616e676550726f746f5001a202044741504962" .
    "0670726f746f33"
));

