<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/context.proto

namespace Google\Api;

use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class Context extends \Google\Protobuf\Internal\Message
{
    private $rules;

    public function getRules()
    {
        return $this->rules;
    }

    public function setRules(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Google\Api\ContextRule::class);
        $this->rules = $var;
    }

}

class ContextRule extends \Google\Protobuf\Internal\Message
{
    private $selector = '';
    private $requested;
    private $provided;

    public function getSelector()
    {
        return $this->selector;
    }

    public function setSelector($var)
    {
        GPBUtil::checkString($var, True);
        $this->selector = $var;
    }

    public function getRequested()
    {
        return $this->requested;
    }

    public function setRequested(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::STRING);
        $this->requested = $var;
    }

    public function getProvided()
    {
        return $this->provided;
    }

    public function setProvided(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::STRING);
        $this->provided = $var;
    }

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0ad0010a18676f6f676c652f6170692f636f6e746578742e70726f746f12" .
    "0a676f6f676c652e61706922310a07436f6e7465787412260a0572756c65" .
    "7318012003280b32172e676f6f676c652e6170692e436f6e746578745275" .
    "6c6522440a0b436f6e7465787452756c6512100a0873656c6563746f7218" .
    "012001280912110a0972657175657374656418022003280912100a087072" .
    "6f766964656418032003280942270a0e636f6d2e676f6f676c652e617069" .
    "420c436f6e7465787450726f746f5001a2020447415049620670726f746f" .
    "33"
));

