<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/distribution.proto

namespace Google\Api;

require_once('google/api/annotations.pb.php');
require_once('google/protobuf/any.pb.php');
require_once('google/protobuf/timestamp.pb.php');
use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class Distribution extends \Google\Protobuf\Internal\Message
{
    private $count = 0;
    private $mean = 0.0;
    private $sum_of_squared_deviation = 0.0;
    private $range = null;
    private $bucket_options = null;
    private $bucket_counts;

    public function getCount()
    {
        return $this->count;
    }

    public function setCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->count = $var;
    }

    public function getMean()
    {
        return $this->mean;
    }

    public function setMean($var)
    {
        GPBUtil::checkDouble($var);
        $this->mean = $var;
    }

    public function getSumOfSquaredDeviation()
    {
        return $this->sum_of_squared_deviation;
    }

    public function setSumOfSquaredDeviation($var)
    {
        GPBUtil::checkDouble($var);
        $this->sum_of_squared_deviation = $var;
    }

    public function getRange()
    {
        return $this->range;
    }

    public function setRange(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Api\Distribution_Range::class);
        $this->range = $var;
    }

    public function getBucketOptions()
    {
        return $this->bucket_options;
    }

    public function setBucketOptions(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Api\Distribution_BucketOptions::class);
        $this->bucket_options = $var;
    }

    public function getBucketCounts()
    {
        return $this->bucket_counts;
    }

    public function setBucketCounts(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::INT64);
        $this->bucket_counts = $var;
    }

}

class Distribution_Range extends \Google\Protobuf\Internal\Message
{
    private $min = 0.0;
    private $max = 0.0;

    public function getMin()
    {
        return $this->min;
    }

    public function setMin($var)
    {
        GPBUtil::checkDouble($var);
        $this->min = $var;
    }

    public function getMax()
    {
        return $this->max;
    }

    public function setMax($var)
    {
        GPBUtil::checkDouble($var);
        $this->max = $var;
    }

}

class Distribution_BucketOptions extends \Google\Protobuf\Internal\Message
{
    protected $options;

    public function getLinearBuckets()
    {
        return $this->readOneof(1);
    }

    public function setLinearBuckets(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Api\Distribution_BucketOptions_Linear::class);
        $this->writeOneof(1, $var);
    }

    public function getExponentialBuckets()
    {
        return $this->readOneof(2);
    }

    public function setExponentialBuckets(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Api\Distribution_BucketOptions_Exponential::class);
        $this->writeOneof(2, $var);
    }

    public function getExplicitBuckets()
    {
        return $this->readOneof(3);
    }

    public function setExplicitBuckets(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Api\Distribution_BucketOptions_Explicit::class);
        $this->writeOneof(3, $var);
    }

    public function getOptions()
    {
        return $this->options;
    }

}

class Distribution_BucketOptions_Linear extends \Google\Protobuf\Internal\Message
{
    private $num_finite_buckets = 0;
    private $width = 0.0;
    private $offset = 0.0;

    public function getNumFiniteBuckets()
    {
        return $this->num_finite_buckets;
    }

    public function setNumFiniteBuckets($var)
    {
        GPBUtil::checkInt32($var);
        $this->num_finite_buckets = $var;
    }

    public function getWidth()
    {
        return $this->width;
    }

    public function setWidth($var)
    {
        GPBUtil::checkDouble($var);
        $this->width = $var;
    }

    public function getOffset()
    {
        return $this->offset;
    }

    public function setOffset($var)
    {
        GPBUtil::checkDouble($var);
        $this->offset = $var;
    }

}

class Distribution_BucketOptions_Exponential extends \Google\Protobuf\Internal\Message
{
    private $num_finite_buckets = 0;
    private $growth_factor = 0.0;
    private $scale = 0.0;

    public function getNumFiniteBuckets()
    {
        return $this->num_finite_buckets;
    }

    public function setNumFiniteBuckets($var)
    {
        GPBUtil::checkInt32($var);
        $this->num_finite_buckets = $var;
    }

    public function getGrowthFactor()
    {
        return $this->growth_factor;
    }

    public function setGrowthFactor($var)
    {
        GPBUtil::checkDouble($var);
        $this->growth_factor = $var;
    }

    public function getScale()
    {
        return $this->scale;
    }

    public function setScale($var)
    {
        GPBUtil::checkDouble($var);
        $this->scale = $var;
    }

}

class Distribution_BucketOptions_Explicit extends \Google\Protobuf\Internal\Message
{
    private $bounds;

    public function getBounds()
    {
        return $this->bounds;
    }

    public function setBounds(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::DOUBLE);
        $this->bounds = $var;
    }

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0ae5060a1d676f6f676c652f6170692f646973747269627574696f6e2e70" .
    "726f746f120a676f6f676c652e6170691a1c676f6f676c652f6170692f61" .
    "6e6e6f746174696f6e732e70726f746f1a19676f6f676c652f70726f746f" .
    "6275662f616e792e70726f746f1a1f676f6f676c652f70726f746f627566" .
    "2f74696d657374616d702e70726f746f22ae050a0c446973747269627574" .
    "696f6e120d0a05636f756e74180120012803120c0a046d65616e18022001" .
    "280112200a1873756d5f6f665f737175617265645f646576696174696f6e" .
    "180320012801122d0a0572616e676518042001280b321e2e676f6f676c65" .
    "2e6170692e446973747269627574696f6e2e52616e6765123e0a0e627563" .
    "6b65745f6f7074696f6e7318062001280b32262e676f6f676c652e617069" .
    "2e446973747269627574696f6e2e4275636b65744f7074696f6e7312150a" .
    "0d6275636b65745f636f756e74731807200328031a210a0552616e676512" .
    "0b0a036d696e180120012801120b0a036d61781802200128011ab5030a0d" .
    "4275636b65744f7074696f6e7312470a0e6c696e6561725f6275636b6574" .
    "7318012001280b322d2e676f6f676c652e6170692e446973747269627574" .
    "696f6e2e4275636b65744f7074696f6e732e4c696e656172480012510a13" .
    "6578706f6e656e7469616c5f6275636b65747318022001280b32322e676f" .
    "6f676c652e6170692e446973747269627574696f6e2e4275636b65744f70" .
    "74696f6e732e4578706f6e656e7469616c4800124b0a106578706c696369" .
    "745f6275636b65747318032001280b322f2e676f6f676c652e6170692e44" .
    "6973747269627574696f6e2e4275636b65744f7074696f6e732e4578706c" .
    "6963697448001a430a064c696e656172121a0a126e756d5f66696e697465" .
    "5f6275636b657473180120012805120d0a05776964746818022001280112" .
    "0e0a066f66667365741803200128011a4f0a0b4578706f6e656e7469616c" .
    "121a0a126e756d5f66696e6974655f6275636b6574731801200128051215" .
    "0a0d67726f7774685f666163746f72180220012801120d0a057363616c65" .
    "1803200128011a1a0a084578706c69636974120e0a06626f756e64731801" .
    "2003280142090a076f7074696f6e7342250a0e636f6d2e676f6f676c652e" .
    "6170694211446973747269627574696f6e50726f746f5001620670726f74" .
    "6f33"
));

