<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/documentation.proto

namespace Google\Api;

use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class Documentation extends \Google\Protobuf\Internal\Message
{
    private $summary = '';
    private $pages;
    private $rules;
    private $documentation_root_url = '';
    private $overview = '';

    public function getSummary()
    {
        return $this->summary;
    }

    public function setSummary($var)
    {
        GPBUtil::checkString($var, True);
        $this->summary = $var;
    }

    public function getPages()
    {
        return $this->pages;
    }

    public function setPages(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Google\Api\Page::class);
        $this->pages = $var;
    }

    public function getRules()
    {
        return $this->rules;
    }

    public function setRules(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Google\Api\DocumentationRule::class);
        $this->rules = $var;
    }

    public function getDocumentationRootUrl()
    {
        return $this->documentation_root_url;
    }

    public function setDocumentationRootUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->documentation_root_url = $var;
    }

    public function getOverview()
    {
        return $this->overview;
    }

    public function setOverview($var)
    {
        GPBUtil::checkString($var, True);
        $this->overview = $var;
    }

}

class DocumentationRule extends \Google\Protobuf\Internal\Message
{
    private $selector = '';
    private $description = '';
    private $deprecation_description = '';

    public function getSelector()
    {
        return $this->selector;
    }

    public function setSelector($var)
    {
        GPBUtil::checkString($var, True);
        $this->selector = $var;
    }

    public function getDescription()
    {
        return $this->description;
    }

    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;
    }

    public function getDeprecationDescription()
    {
        return $this->deprecation_description;
    }

    public function setDeprecationDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->deprecation_description = $var;
    }

}

class Page extends \Google\Protobuf\Internal\Message
{
    private $name = '';
    private $content = '';
    private $subpages;

    public function getName()
    {
        return $this->name;
    }

    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

    public function getContent()
    {
        return $this->content;
    }

    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->content = $var;
    }

    public function getSubpages()
    {
        return $this->subpages;
    }

    public function setSubpages(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Google\Api\Page::class);
        $this->subpages = $var;
    }

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0aaf030a1e676f6f676c652f6170692f646f63756d656e746174696f6e2e" .
    "70726f746f120a676f6f676c652e61706922a1010a0d446f63756d656e74" .
    "6174696f6e120f0a0773756d6d617279180120012809121f0a0570616765" .
    "7318052003280b32102e676f6f676c652e6170692e50616765122c0a0572" .
    "756c657318032003280b321d2e676f6f676c652e6170692e446f63756d65" .
    "6e746174696f6e52756c65121e0a16646f63756d656e746174696f6e5f72" .
    "6f6f745f75726c18042001280912100a086f766572766965771802200128" .
    "09225b0a11446f63756d656e746174696f6e52756c6512100a0873656c65" .
    "63746f7218012001280912130a0b6465736372697074696f6e1802200128" .
    "09121f0a176465707265636174696f6e5f6465736372697074696f6e1803" .
    "2001280922490a0450616765120c0a046e616d65180120012809120f0a07" .
    "636f6e74656e7418022001280912220a0873756270616765731803200328" .
    "0b32102e676f6f676c652e6170692e50616765422d0a0e636f6d2e676f6f" .
    "676c652e6170694212446f63756d656e746174696f6e50726f746f5001a2" .
    "020447415049620670726f746f33"
));

