<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/endpoint.proto

namespace Google\Api;

require_once('google/api/annotations.pb.php');
use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class Endpoint extends \Google\Protobuf\Internal\Message
{
    private $name = '';
    private $aliases;
    private $apis;
    private $features;
    private $allow_cors = false;

    public function getName()
    {
        return $this->name;
    }

    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

    public function getAliases()
    {
        return $this->aliases;
    }

    public function setAliases(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::STRING);
        $this->aliases = $var;
    }

    public function getApis()
    {
        return $this->apis;
    }

    public function setApis(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::STRING);
        $this->apis = $var;
    }

    public function getFeatures()
    {
        return $this->features;
    }

    public function setFeatures(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::STRING);
        $this->features = $var;
    }

    public function getAllowCors()
    {
        return $this->allow_cors;
    }

    public function setAllowCors($var)
    {
        GPBUtil::checkBool($var);
        $this->allow_cors = $var;
    }

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0ad6010a19676f6f676c652f6170692f656e64706f696e742e70726f746f" .
    "120a676f6f676c652e6170691a1c676f6f676c652f6170692f616e6e6f74" .
    "6174696f6e732e70726f746f225d0a08456e64706f696e74120c0a046e61" .
    "6d65180120012809120f0a07616c6961736573180220032809120c0a0461" .
    "70697318032003280912100a08666561747572657318042003280912120a" .
    "0a616c6c6f775f636f727318052001280842280a0e636f6d2e676f6f676c" .
    "652e617069420d456e64706f696e7450726f746f5001a202044741504962" .
    "0670726f746f33"
));

