<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/logging.proto

namespace Google\Api;

require_once('google/api/annotations.pb.php');
use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class Logging extends \Google\Protobuf\Internal\Message
{
    private $producer_destinations;
    private $consumer_destinations;

    public function getProducerDestinations()
    {
        return $this->producer_destinations;
    }

    public function setProducerDestinations(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Google\Api\Logging_LoggingDestination::class);
        $this->producer_destinations = $var;
    }

    public function getConsumerDestinations()
    {
        return $this->consumer_destinations;
    }

    public function setConsumerDestinations(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Google\Api\Logging_LoggingDestination::class);
        $this->consumer_destinations = $var;
    }

}

class Logging_LoggingDestination extends \Google\Protobuf\Internal\Message
{
    private $monitored_resource = '';
    private $logs;

    public function getMonitoredResource()
    {
        return $this->monitored_resource;
    }

    public function setMonitoredResource($var)
    {
        GPBUtil::checkString($var, True);
        $this->monitored_resource = $var;
    }

    public function getLogs()
    {
        return $this->logs;
    }

    public function setLogs(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::STRING);
        $this->logs = $var;
    }

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0acf020a18676f6f676c652f6170692f6c6f6767696e672e70726f746f12" .
    "0a676f6f676c652e6170691a1c676f6f676c652f6170692f616e6e6f7461" .
    "74696f6e732e70726f746f22d7010a074c6f6767696e6712450a1570726f" .
    "64756365725f64657374696e6174696f6e7318012003280b32262e676f6f" .
    "676c652e6170692e4c6f6767696e672e4c6f6767696e6744657374696e61" .
    "74696f6e12450a15636f6e73756d65725f64657374696e6174696f6e7318" .
    "022003280b32262e676f6f676c652e6170692e4c6f6767696e672e4c6f67" .
    "67696e6744657374696e6174696f6e1a3e0a124c6f6767696e6744657374" .
    "696e6174696f6e121a0a126d6f6e69746f7265645f7265736f7572636518" .
    "0320012809120c0a046c6f677318012003280942270a0e636f6d2e676f6f" .
    "676c652e617069420c4c6f6767696e6750726f746f5001a2020447415049" .
    "620670726f746f33"
));

