<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/metric.proto

namespace Google\Api;

require_once('google/api/label.pb.php');
use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class MetricDescriptor extends \Google\Protobuf\Internal\Message
{
    private $name = '';
    private $type = '';
    private $labels;
    private $metric_kind = 0;
    private $value_type = 0;
    private $unit = '';
    private $description = '';
    private $display_name = '';

    public function getName()
    {
        return $this->name;
    }

    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

    public function getType()
    {
        return $this->type;
    }

    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;
    }

    public function getLabels()
    {
        return $this->labels;
    }

    public function setLabels(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Google\Api\LabelDescriptor::class);
        $this->labels = $var;
    }

    public function getMetricKind()
    {
        return $this->metric_kind;
    }

    public function setMetricKind($var)
    {
        GPBUtil::checkEnum($var, \Google\Api\MetricDescriptor_MetricKind::class);
        $this->metric_kind = $var;
    }

    public function getValueType()
    {
        return $this->value_type;
    }

    public function setValueType($var)
    {
        GPBUtil::checkEnum($var, \Google\Api\MetricDescriptor_ValueType::class);
        $this->value_type = $var;
    }

    public function getUnit()
    {
        return $this->unit;
    }

    public function setUnit($var)
    {
        GPBUtil::checkString($var, True);
        $this->unit = $var;
    }

    public function getDescription()
    {
        return $this->description;
    }

    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;
    }

    public function getDisplayName()
    {
        return $this->display_name;
    }

    public function setDisplayName($var)
    {
        GPBUtil::checkString($var, True);
        $this->display_name = $var;
    }

}

class MetricDescriptor_MetricKind
{
    const METRIC_KIND_UNSPECIFIED = 0;
    const GAUGE = 1;
    const DELTA = 2;
    const CUMULATIVE = 3;
}

class MetricDescriptor_ValueType
{
    const VALUE_TYPE_UNSPECIFIED = 0;
    const BOOL = 1;
    const INT64 = 2;
    const DOUBLE = 3;
    const STRING = 4;
    const DISTRIBUTION = 5;
    const MONEY = 6;
}

class Metric extends \Google\Protobuf\Internal\Message
{
    private $type = '';
    private $labels;

    public function getType()
    {
        return $this->type;
    }

    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;
    }

    public function getLabels()
    {
        return $this->labels;
    }

    public function setLabels(&$var)
    {
        $this->labels = $var;
    }

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0ab9050a17676f6f676c652f6170692f6d65747269632e70726f746f120a" .
    "676f6f676c652e6170691a16676f6f676c652f6170692f6c6162656c2e70" .
    "726f746f22d2030a104d657472696344657363726970746f72120c0a046e" .
    "616d65180120012809120c0a0474797065180820012809122b0a066c6162" .
    "656c7318022003280b321b2e676f6f676c652e6170692e4c6162656c4465" .
    "7363726970746f72123c0a0b6d65747269635f6b696e6418032001280e32" .
    "272e676f6f676c652e6170692e4d657472696344657363726970746f722e" .
    "4d65747269634b696e64123a0a0a76616c75655f7479706518042001280e" .
    "32262e676f6f676c652e6170692e4d657472696344657363726970746f72" .
    "2e56616c756554797065120c0a04756e697418052001280912130a0b6465" .
    "736372697074696f6e18062001280912140a0c646973706c61795f6e616d" .
    "65180720012809224f0a0a4d65747269634b696e64121b0a174d45545249" .
    "435f4b494e445f554e535045434946494544100012090a05474155474510" .
    "0112090a0544454c54411002120e0a0a43554d554c415449564510032271" .
    "0a0956616c756554797065121a0a1656414c55455f545950455f554e5350" .
    "45434946494544100012080a04424f4f4c100112090a05494e5436341002" .
    "120a0a06444f55424c451003120a0a06535452494e47100412100a0c4449" .
    "53545249425554494f4e100512090a054d4f4e4559100622750a064d6574" .
    "726963120c0a0474797065180320012809122e0a066c6162656c73180220" .
    "03280b321e2e676f6f676c652e6170692e4d65747269632e4c6162656c73" .
    "456e7472791a2d0a0b4c6162656c73456e747279120b0a036b6579180120" .
    "012809120d0a0576616c75651802200128093a02380142260a0e636f6d2e" .
    "676f6f676c652e617069420b4d657472696350726f746f5001a202044741" .
    "5049620670726f746f33"
));

