<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/monitoring.proto

namespace Google\Api;

require_once('google/api/annotations.pb.php');
use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class Monitoring extends \Google\Protobuf\Internal\Message
{
    private $producer_destinations;
    private $consumer_destinations;

    public function getProducerDestinations()
    {
        return $this->producer_destinations;
    }

    public function setProducerDestinations(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Google\Api\Monitoring_MonitoringDestination::class);
        $this->producer_destinations = $var;
    }

    public function getConsumerDestinations()
    {
        return $this->consumer_destinations;
    }

    public function setConsumerDestinations(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Google\Api\Monitoring_MonitoringDestination::class);
        $this->consumer_destinations = $var;
    }

}

class Monitoring_MonitoringDestination extends \Google\Protobuf\Internal\Message
{
    private $monitored_resource = '';
    private $metrics;

    public function getMonitoredResource()
    {
        return $this->monitored_resource;
    }

    public function setMonitoredResource($var)
    {
        GPBUtil::checkString($var, True);
        $this->monitored_resource = $var;
    }

    public function getMetrics()
    {
        return $this->metrics;
    }

    public function setMetrics(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::STRING);
        $this->metrics = $var;
    }

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0aea020a1b676f6f676c652f6170692f6d6f6e69746f72696e672e70726f" .
    "746f120a676f6f676c652e6170691a1c676f6f676c652f6170692f616e6e" .
    "6f746174696f6e732e70726f746f22ec010a0a4d6f6e69746f72696e6712" .
    "4b0a1570726f64756365725f64657374696e6174696f6e7318012003280b" .
    "322c2e676f6f676c652e6170692e4d6f6e69746f72696e672e4d6f6e6974" .
    "6f72696e6744657374696e6174696f6e124b0a15636f6e73756d65725f64" .
    "657374696e6174696f6e7318022003280b322c2e676f6f676c652e617069" .
    "2e4d6f6e69746f72696e672e4d6f6e69746f72696e6744657374696e6174" .
    "696f6e1a440a154d6f6e69746f72696e6744657374696e6174696f6e121a" .
    "0a126d6f6e69746f7265645f7265736f75726365180120012809120f0a07" .
    "6d657472696373180220032809422a0a0e636f6d2e676f6f676c652e6170" .
    "69420f4d6f6e69746f72696e6750726f746f5001a2020447415049620670" .
    "726f746f33"
));

