<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/monitoring/v3/metric.proto

namespace GPBMetadata\Google\Monitoring\V3;

class Metric
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Metric::initOnce();
        \GPBMetadata\Google\Api\MonitoredResource::initOnce();
        \GPBMetadata\Google\Monitoring\V3\Common::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa6050a21676f6f676c652f6d6f6e69746f72696e672f76332f6d657472" .
            "69632e70726f746f1214676f6f676c652e6d6f6e69746f72696e672e7633" .
            "1a17676f6f676c652f6170692f6d65747269632e70726f746f1a23676f6f" .
            "676c652f6170692f6d6f6e69746f7265645f7265736f757263652e70726f" .
            "746f1a21676f6f676c652f6d6f6e69746f72696e672f76332f636f6d6d6f" .
            "6e2e70726f746f226e0a05506f696e7412340a08696e74657276616c1801" .
            "2001280b32222e676f6f676c652e6d6f6e69746f72696e672e76332e5469" .
            "6d65496e74657276616c122f0a0576616c756518022001280b32202e676f" .
            "6f676c652e6d6f6e69746f72696e672e76332e547970656456616c756522" .
            "88020a0a54696d6553657269657312220a066d657472696318012001280b" .
            "32122e676f6f676c652e6170692e4d6574726963122f0a087265736f7572" .
            "636518022001280b321d2e676f6f676c652e6170692e4d6f6e69746f7265" .
            "645265736f75726365123c0a0b6d65747269635f6b696e6418032001280e" .
            "32272e676f6f676c652e6170692e4d657472696344657363726970746f72" .
            "2e4d65747269634b696e64123a0a0a76616c75655f747970651804200128" .
            "0e32262e676f6f676c652e6170692e4d657472696344657363726970746f" .
            "722e56616c756554797065122b0a06706f696e747318052003280b321b2e" .
            "676f6f676c652e6d6f6e69746f72696e672e76332e506f696e744286010a" .
            "18636f6d2e676f6f676c652e6d6f6e69746f72696e672e7633420b4d6574" .
            "72696350726f746f50015a3e676f6f676c652e676f6c616e672e6f72672f" .
            "67656e70726f746f2f676f6f676c65617069732f6d6f6e69746f72696e67" .
            "2f76333b6d6f6e69746f72696e67aa021a476f6f676c652e436c6f75642e" .
            "4d6f6e69746f72696e672e5633620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

