<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/servicemanagement/v1/resources.proto

namespace Google\Api\Servicemanagement\V1;

/**
 * Protobuf enum <code>google.api.servicemanagement.v1.ConfigFile.FileType</code>
 */
class ConfigFile_FileType
{
    /**
     * <pre>
     * Unknown file type.
     * </pre>
     *
     * <code>FILE_TYPE_UNSPECIFIED = 0;</code>
     */
    const FILE_TYPE_UNSPECIFIED = 0;
    /**
     * <pre>
     * YAML-specification of service.
     * </pre>
     *
     * <code>SERVICE_CONFIG_YAML = 1;</code>
     */
    const SERVICE_CONFIG_YAML = 1;
    /**
     * <pre>
     * OpenAPI specification, serialized in JSON.
     * </pre>
     *
     * <code>OPEN_API_JSON = 2;</code>
     */
    const OPEN_API_JSON = 2;
    /**
     * <pre>
     * OpenAPI specification, serialized in YAML.
     * </pre>
     *
     * <code>OPEN_API_YAML = 3;</code>
     */
    const OPEN_API_YAML = 3;
    /**
     * <pre>
     * FileDescriptorSet, generated by protoc.
     * To generate, use protoc with imports and source info included.
     * For an example test.proto file, the following command would put the value
     * in a new file named out.pb.
     * $protoc --include_imports --include_source_info test.proto -o out.pb
     * </pre>
     *
     * <code>FILE_DESCRIPTOR_SET_PROTO = 4;</code>
     */
    const FILE_DESCRIPTOR_SET_PROTO = 4;
}

