<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/servicemanagement/v1/resources.proto

namespace Google\Api\Servicemanagement\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Generic specification of a source configuration file
 * </pre>
 *
 * Protobuf type <code>google.api.servicemanagement.v1.ConfigFile</code>
 */
class ConfigFile extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The file name of the configuration file (full or relative path).
     * </pre>
     *
     * <code>string file_path = 1;</code>
     */
    private $file_path = '';
    /**
     * <pre>
     * The bytes that constitute the file.
     * </pre>
     *
     * <code>bytes file_contents = 3;</code>
     */
    private $file_contents = '';
    /**
     * <pre>
     * The type of configuration file this represents.
     * </pre>
     *
     * <code>.google.api.servicemanagement.v1.ConfigFile.FileType file_type = 4;</code>
     */
    private $file_type = 0;

    public function __construct() {
        \GPBMetadata\Google\Api\Servicemanagement\V1\Resources::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The file name of the configuration file (full or relative path).
     * </pre>
     *
     * <code>string file_path = 1;</code>
     */
    public function getFilePath()
    {
        return $this->file_path;
    }

    /**
     * <pre>
     * The file name of the configuration file (full or relative path).
     * </pre>
     *
     * <code>string file_path = 1;</code>
     */
    public function setFilePath($var)
    {
        GPBUtil::checkString($var, True);
        $this->file_path = $var;
    }

    /**
     * <pre>
     * The bytes that constitute the file.
     * </pre>
     *
     * <code>bytes file_contents = 3;</code>
     */
    public function getFileContents()
    {
        return $this->file_contents;
    }

    /**
     * <pre>
     * The bytes that constitute the file.
     * </pre>
     *
     * <code>bytes file_contents = 3;</code>
     */
    public function setFileContents($var)
    {
        GPBUtil::checkString($var, False);
        $this->file_contents = $var;
    }

    /**
     * <pre>
     * The type of configuration file this represents.
     * </pre>
     *
     * <code>.google.api.servicemanagement.v1.ConfigFile.FileType file_type = 4;</code>
     */
    public function getFileType()
    {
        return $this->file_type;
    }

    /**
     * <pre>
     * The type of configuration file this represents.
     * </pre>
     *
     * <code>.google.api.servicemanagement.v1.ConfigFile.FileType file_type = 4;</code>
     */
    public function setFileType($var)
    {
        GPBUtil::checkEnum($var, \Google\Api\Servicemanagement\V1\ConfigFile_FileType::class);
        $this->file_type = $var;
    }

}

