<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/servicemanagement/v1/resources.proto

namespace Google\Api\Servicemanagement\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Represents a source file which is used to generate the service configuration
 * defined by `google.api.Service`.
 * </pre>
 *
 * Protobuf type <code>google.api.servicemanagement.v1.ConfigSource</code>
 */
class ConfigSource extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * A unique ID for a specific instance of this message, typically assigned
     * by the client for tracking purpose. If empty, the server may choose to
     * generate one instead.
     * </pre>
     *
     * <code>string id = 5;</code>
     */
    private $id = '';
    /**
     * <pre>
     * Set of source configuration files that are used to generate a service
     * configuration (`google.api.Service`).
     * </pre>
     *
     * <code>repeated .google.api.servicemanagement.v1.ConfigFile files = 2;</code>
     */
    private $files;

    public function __construct() {
        \GPBMetadata\Google\Api\Servicemanagement\V1\Resources::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * A unique ID for a specific instance of this message, typically assigned
     * by the client for tracking purpose. If empty, the server may choose to
     * generate one instead.
     * </pre>
     *
     * <code>string id = 5;</code>
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * <pre>
     * A unique ID for a specific instance of this message, typically assigned
     * by the client for tracking purpose. If empty, the server may choose to
     * generate one instead.
     * </pre>
     *
     * <code>string id = 5;</code>
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;
    }

    /**
     * <pre>
     * Set of source configuration files that are used to generate a service
     * configuration (`google.api.Service`).
     * </pre>
     *
     * <code>repeated .google.api.servicemanagement.v1.ConfigFile files = 2;</code>
     */
    public function getFiles()
    {
        return $this->files;
    }

    /**
     * <pre>
     * Set of source configuration files that are used to generate a service
     * configuration (`google.api.Service`).
     * </pre>
     *
     * <code>repeated .google.api.servicemanagement.v1.ConfigFile files = 2;</code>
     */
    public function setFiles(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Api\Servicemanagement\V1\ConfigFile::class);
        $this->files = $arr;
    }

}

