<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/servicemanagement/v1/servicemanager.proto

namespace Google\Api\Servicemanagement\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Response message for GenerateConfigReport method.
 * </pre>
 *
 * Protobuf type <code>google.api.servicemanagement.v1.GenerateConfigReportResponse</code>
 */
class GenerateConfigReportResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * Name of the service this report belongs to.
     * </pre>
     *
     * <code>string service_name = 1;</code>
     */
    private $service_name = '';
    /**
     * <pre>
     * ID of the service configuration this report belongs to.
     * </pre>
     *
     * <code>string id = 2;</code>
     */
    private $id = '';
    /**
     * <pre>
     * list of ChangeReport, each corresponding to comparison between two
     * service configurations.
     * </pre>
     *
     * <code>repeated .google.api.servicemanagement.v1.ChangeReport change_reports = 3;</code>
     */
    private $change_reports;
    /**
     * <pre>
     * Errors / Linter warnings associated with the service definition this
     * report
     * belongs to.
     * </pre>
     *
     * <code>repeated .google.api.servicemanagement.v1.Diagnostic diagnostics = 4;</code>
     */
    private $diagnostics;

    public function __construct() {
        \GPBMetadata\Google\Api\Servicemanagement\V1\Servicemanager::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Name of the service this report belongs to.
     * </pre>
     *
     * <code>string service_name = 1;</code>
     */
    public function getServiceName()
    {
        return $this->service_name;
    }

    /**
     * <pre>
     * Name of the service this report belongs to.
     * </pre>
     *
     * <code>string service_name = 1;</code>
     */
    public function setServiceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->service_name = $var;
    }

    /**
     * <pre>
     * ID of the service configuration this report belongs to.
     * </pre>
     *
     * <code>string id = 2;</code>
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * <pre>
     * ID of the service configuration this report belongs to.
     * </pre>
     *
     * <code>string id = 2;</code>
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;
    }

    /**
     * <pre>
     * list of ChangeReport, each corresponding to comparison between two
     * service configurations.
     * </pre>
     *
     * <code>repeated .google.api.servicemanagement.v1.ChangeReport change_reports = 3;</code>
     */
    public function getChangeReports()
    {
        return $this->change_reports;
    }

    /**
     * <pre>
     * list of ChangeReport, each corresponding to comparison between two
     * service configurations.
     * </pre>
     *
     * <code>repeated .google.api.servicemanagement.v1.ChangeReport change_reports = 3;</code>
     */
    public function setChangeReports(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Api\Servicemanagement\V1\ChangeReport::class);
        $this->change_reports = $arr;
    }

    /**
     * <pre>
     * Errors / Linter warnings associated with the service definition this
     * report
     * belongs to.
     * </pre>
     *
     * <code>repeated .google.api.servicemanagement.v1.Diagnostic diagnostics = 4;</code>
     */
    public function getDiagnostics()
    {
        return $this->diagnostics;
    }

    /**
     * <pre>
     * Errors / Linter warnings associated with the service definition this
     * report
     * belongs to.
     * </pre>
     *
     * <code>repeated .google.api.servicemanagement.v1.Diagnostic diagnostics = 4;</code>
     */
    public function setDiagnostics(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Api\Servicemanagement\V1\Diagnostic::class);
        $this->diagnostics = $arr;
    }

}

