<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/servicemanagement/v1/servicemanager.proto

namespace Google\Api\Servicemanagement\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Response message for `ListServices` method.
 * </pre>
 *
 * Protobuf type <code>google.api.servicemanagement.v1.ListServicesResponse</code>
 */
class ListServicesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The results of the query.
     * </pre>
     *
     * <code>repeated .google.api.servicemanagement.v1.ManagedService services = 1;</code>
     */
    private $services;
    /**
     * <pre>
     * Token that can be passed to `ListServices` to resume a paginated query.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     */
    private $next_page_token = '';

    public function __construct() {
        \GPBMetadata\Google\Api\Servicemanagement\V1\Servicemanager::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The results of the query.
     * </pre>
     *
     * <code>repeated .google.api.servicemanagement.v1.ManagedService services = 1;</code>
     */
    public function getServices()
    {
        return $this->services;
    }

    /**
     * <pre>
     * The results of the query.
     * </pre>
     *
     * <code>repeated .google.api.servicemanagement.v1.ManagedService services = 1;</code>
     */
    public function setServices(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Api\Servicemanagement\V1\ManagedService::class);
        $this->services = $arr;
    }

    /**
     * <pre>
     * Token that can be passed to `ListServices` to resume a paginated query.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     */
    public function getNextPageToken()
    {
        return $this->next_page_token;
    }

    /**
     * <pre>
     * Token that can be passed to `ListServices` to resume a paginated query.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     */
    public function setNextPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->next_page_token = $var;
    }

}

