<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/servicemanagement/v1/servicemanager.proto

namespace Google\Api\Servicemanagement\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Request message for `ListServices` method.
 * </pre>
 *
 * Protobuf type <code>google.api.servicemanagement.v1.ListServicesRequest</code>
 */
class ListServicesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * Include services produced by the specified project.
     * </pre>
     *
     * <code>string producer_project_id = 1;</code>
     */
    private $producer_project_id = '';
    /**
     * <pre>
     * Requested size of the next page of data.
     * </pre>
     *
     * <code>int32 page_size = 5;</code>
     */
    private $page_size = 0;
    /**
     * <pre>
     * Token identifying which result to start with; returned by a previous list
     * call.
     * </pre>
     *
     * <code>string page_token = 6;</code>
     */
    private $page_token = '';

    public function __construct() {
        \GPBMetadata\Google\Api\Servicemanagement\V1\Servicemanager::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Include services produced by the specified project.
     * </pre>
     *
     * <code>string producer_project_id = 1;</code>
     */
    public function getProducerProjectId()
    {
        return $this->producer_project_id;
    }

    /**
     * <pre>
     * Include services produced by the specified project.
     * </pre>
     *
     * <code>string producer_project_id = 1;</code>
     */
    public function setProducerProjectId($var)
    {
        GPBUtil::checkString($var, True);
        $this->producer_project_id = $var;
    }

    /**
     * <pre>
     * Requested size of the next page of data.
     * </pre>
     *
     * <code>int32 page_size = 5;</code>
     */
    public function getPageSize()
    {
        return $this->page_size;
    }

    /**
     * <pre>
     * Requested size of the next page of data.
     * </pre>
     *
     * <code>int32 page_size = 5;</code>
     */
    public function setPageSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->page_size = $var;
    }

    /**
     * <pre>
     * Token identifying which result to start with; returned by a previous list
     * call.
     * </pre>
     *
     * <code>string page_token = 6;</code>
     */
    public function getPageToken()
    {
        return $this->page_token;
    }

    /**
     * <pre>
     * Token identifying which result to start with; returned by a previous list
     * call.
     * </pre>
     *
     * <code>string page_token = 6;</code>
     */
    public function setPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->page_token = $var;
    }

}

