<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/servicemanagement/v1/resources.proto

namespace Google\Api\Servicemanagement\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * The metadata associated with a long running operation resource.
 * </pre>
 *
 * Protobuf type <code>google.api.servicemanagement.v1.OperationMetadata</code>
 */
class OperationMetadata extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The full name of the resources that this operation is directly
     * associated with.
     * </pre>
     *
     * <code>repeated string resource_names = 1;</code>
     */
    private $resource_names;
    /**
     * <pre>
     * Detailed status information for each step. The order is undetermined.
     * </pre>
     *
     * <code>repeated .google.api.servicemanagement.v1.OperationMetadata.Step steps = 2;</code>
     */
    private $steps;
    /**
     * <pre>
     * Percentage of completion of this operation, ranging from 0 to 100.
     * </pre>
     *
     * <code>int32 progress_percentage = 3;</code>
     */
    private $progress_percentage = 0;
    /**
     * <pre>
     * The start time of the operation.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp start_time = 4;</code>
     */
    private $start_time = null;

    public function __construct() {
        \GPBMetadata\Google\Api\Servicemanagement\V1\Resources::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The full name of the resources that this operation is directly
     * associated with.
     * </pre>
     *
     * <code>repeated string resource_names = 1;</code>
     */
    public function getResourceNames()
    {
        return $this->resource_names;
    }

    /**
     * <pre>
     * The full name of the resources that this operation is directly
     * associated with.
     * </pre>
     *
     * <code>repeated string resource_names = 1;</code>
     */
    public function setResourceNames(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->resource_names = $arr;
    }

    /**
     * <pre>
     * Detailed status information for each step. The order is undetermined.
     * </pre>
     *
     * <code>repeated .google.api.servicemanagement.v1.OperationMetadata.Step steps = 2;</code>
     */
    public function getSteps()
    {
        return $this->steps;
    }

    /**
     * <pre>
     * Detailed status information for each step. The order is undetermined.
     * </pre>
     *
     * <code>repeated .google.api.servicemanagement.v1.OperationMetadata.Step steps = 2;</code>
     */
    public function setSteps(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Api\Servicemanagement\V1\OperationMetadata_Step::class);
        $this->steps = $arr;
    }

    /**
     * <pre>
     * Percentage of completion of this operation, ranging from 0 to 100.
     * </pre>
     *
     * <code>int32 progress_percentage = 3;</code>
     */
    public function getProgressPercentage()
    {
        return $this->progress_percentage;
    }

    /**
     * <pre>
     * Percentage of completion of this operation, ranging from 0 to 100.
     * </pre>
     *
     * <code>int32 progress_percentage = 3;</code>
     */
    public function setProgressPercentage($var)
    {
        GPBUtil::checkInt32($var);
        $this->progress_percentage = $var;
    }

    /**
     * <pre>
     * The start time of the operation.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp start_time = 4;</code>
     */
    public function getStartTime()
    {
        return $this->start_time;
    }

    /**
     * <pre>
     * The start time of the operation.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp start_time = 4;</code>
     */
    public function setStartTime(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->start_time = $var;
    }

}

