<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/servicemanagement/v1/resources.proto

namespace Google\Api\Servicemanagement\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Strategy that specifies how Google Service Control should select
 * different
 * versions of service configurations based on traffic percentage.
 * One example of how to gradually rollout a new service configuration using
 * this
 * strategy:
 * Day 1
 *     Rollout {
 *       id: "example.googleapis.com/rollout_20160206"
 *       traffic_percent_strategy {
 *         percentages: {
 *           "example.googleapis.com/20160201": 70.00
 *           "example.googleapis.com/20160206": 30.00
 *         }
 *       }
 *     }
 * Day 2
 *     Rollout {
 *       id: "example.googleapis.com/rollout_20160207"
 *       traffic_percent_strategy: {
 *         percentages: {
 *           "example.googleapis.com/20160206": 100.00
 *         }
 *       }
 *     }
 * </pre>
 *
 * Protobuf type <code>google.api.servicemanagement.v1.Rollout.TrafficPercentStrategy</code>
 */
class Rollout_TrafficPercentStrategy extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * Maps service configuration IDs to their corresponding traffic percentage.
     * Key is the service configuration ID, Value is the traffic percentage
     * which must be greater than 0.0 and the sum must equal to 100.0.
     * </pre>
     *
     * <code>map&lt;string, double&gt; percentages = 1;</code>
     */
    private $percentages;

    public function __construct() {
        \GPBMetadata\Google\Api\Servicemanagement\V1\Resources::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Maps service configuration IDs to their corresponding traffic percentage.
     * Key is the service configuration ID, Value is the traffic percentage
     * which must be greater than 0.0 and the sum must equal to 100.0.
     * </pre>
     *
     * <code>map&lt;string, double&gt; percentages = 1;</code>
     */
    public function getPercentages()
    {
        return $this->percentages;
    }

    /**
     * <pre>
     * Maps service configuration IDs to their corresponding traffic percentage.
     * Key is the service configuration ID, Value is the traffic percentage
     * which must be greater than 0.0 and the sum must equal to 100.0.
     * </pre>
     *
     * <code>map&lt;string, double&gt; percentages = 1;</code>
     */
    public function setPercentages(&$var)
    {
        $this->percentages = $var;
    }

}

