<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/servicemanagement/v1/resources.proto

namespace Google\Api\Servicemanagement\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * A rollout resource that defines how service configuration versions are pushed
 * to control plane systems. Typically, you create a new version of the
 * service config, and then create a Rollout to push the service config.
 * </pre>
 *
 * Protobuf type <code>google.api.servicemanagement.v1.Rollout</code>
 */
class Rollout extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * Optional unique identifier of this Rollout. Only lower case letters, digits
     *  and '-' are allowed.
     * If not specified by client, the server will generate one. The generated id
     * will have the form of &lt;date&gt;&lt;revision number&gt;, where "date" is the create
     * date in ISO 8601 format.  "revision number" is a monotonically increasing
     * positive number that is reset every day for each service.
     * An example of the generated rollout_id is '2016-02-16r1'
     * </pre>
     *
     * <code>string rollout_id = 1;</code>
     */
    private $rollout_id = '';
    /**
     * <pre>
     * Creation time of the rollout. Readonly.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp create_time = 2;</code>
     */
    private $create_time = null;
    /**
     * <pre>
     * The user who created the Rollout. Readonly.
     * </pre>
     *
     * <code>string created_by = 3;</code>
     */
    private $created_by = '';
    /**
     * <pre>
     * The status of this rollout. Readonly. In case of a failed rollout,
     * the system will automatically rollback to the current Rollout
     * version. Readonly.
     * </pre>
     *
     * <code>.google.api.servicemanagement.v1.Rollout.RolloutStatus status = 4;</code>
     */
    private $status = 0;
    /**
     * <pre>
     * The name of the service associated with this Rollout.
     * </pre>
     *
     * <code>string service_name = 8;</code>
     */
    private $service_name = '';
    protected $strategy;

    public function __construct() {
        \GPBMetadata\Google\Api\Servicemanagement\V1\Resources::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Optional unique identifier of this Rollout. Only lower case letters, digits
     *  and '-' are allowed.
     * If not specified by client, the server will generate one. The generated id
     * will have the form of &lt;date&gt;&lt;revision number&gt;, where "date" is the create
     * date in ISO 8601 format.  "revision number" is a monotonically increasing
     * positive number that is reset every day for each service.
     * An example of the generated rollout_id is '2016-02-16r1'
     * </pre>
     *
     * <code>string rollout_id = 1;</code>
     */
    public function getRolloutId()
    {
        return $this->rollout_id;
    }

    /**
     * <pre>
     * Optional unique identifier of this Rollout. Only lower case letters, digits
     *  and '-' are allowed.
     * If not specified by client, the server will generate one. The generated id
     * will have the form of &lt;date&gt;&lt;revision number&gt;, where "date" is the create
     * date in ISO 8601 format.  "revision number" is a monotonically increasing
     * positive number that is reset every day for each service.
     * An example of the generated rollout_id is '2016-02-16r1'
     * </pre>
     *
     * <code>string rollout_id = 1;</code>
     */
    public function setRolloutId($var)
    {
        GPBUtil::checkString($var, True);
        $this->rollout_id = $var;
    }

    /**
     * <pre>
     * Creation time of the rollout. Readonly.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp create_time = 2;</code>
     */
    public function getCreateTime()
    {
        return $this->create_time;
    }

    /**
     * <pre>
     * Creation time of the rollout. Readonly.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp create_time = 2;</code>
     */
    public function setCreateTime(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->create_time = $var;
    }

    /**
     * <pre>
     * The user who created the Rollout. Readonly.
     * </pre>
     *
     * <code>string created_by = 3;</code>
     */
    public function getCreatedBy()
    {
        return $this->created_by;
    }

    /**
     * <pre>
     * The user who created the Rollout. Readonly.
     * </pre>
     *
     * <code>string created_by = 3;</code>
     */
    public function setCreatedBy($var)
    {
        GPBUtil::checkString($var, True);
        $this->created_by = $var;
    }

    /**
     * <pre>
     * The status of this rollout. Readonly. In case of a failed rollout,
     * the system will automatically rollback to the current Rollout
     * version. Readonly.
     * </pre>
     *
     * <code>.google.api.servicemanagement.v1.Rollout.RolloutStatus status = 4;</code>
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * <pre>
     * The status of this rollout. Readonly. In case of a failed rollout,
     * the system will automatically rollback to the current Rollout
     * version. Readonly.
     * </pre>
     *
     * <code>.google.api.servicemanagement.v1.Rollout.RolloutStatus status = 4;</code>
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Google\Api\Servicemanagement\V1\Rollout_RolloutStatus::class);
        $this->status = $var;
    }

    /**
     * <pre>
     * Google Service Control selects service configurations based on
     * traffic percentage.
     * </pre>
     *
     * <code>.google.api.servicemanagement.v1.Rollout.TrafficPercentStrategy traffic_percent_strategy = 5;</code>
     */
    public function getTrafficPercentStrategy()
    {
        return $this->readOneof(5);
    }

    /**
     * <pre>
     * Google Service Control selects service configurations based on
     * traffic percentage.
     * </pre>
     *
     * <code>.google.api.servicemanagement.v1.Rollout.TrafficPercentStrategy traffic_percent_strategy = 5;</code>
     */
    public function setTrafficPercentStrategy(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Api\Servicemanagement\V1\Rollout_TrafficPercentStrategy::class);
        $this->writeOneof(5, $var);
    }

    /**
     * <pre>
     * The strategy associated with a rollout to delete a `ManagedService`.
     * Readonly.
     * </pre>
     *
     * <code>.google.api.servicemanagement.v1.Rollout.DeleteServiceStrategy delete_service_strategy = 200;</code>
     */
    public function getDeleteServiceStrategy()
    {
        return $this->readOneof(200);
    }

    /**
     * <pre>
     * The strategy associated with a rollout to delete a `ManagedService`.
     * Readonly.
     * </pre>
     *
     * <code>.google.api.servicemanagement.v1.Rollout.DeleteServiceStrategy delete_service_strategy = 200;</code>
     */
    public function setDeleteServiceStrategy(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Api\Servicemanagement\V1\Rollout_DeleteServiceStrategy::class);
        $this->writeOneof(200, $var);
    }

    /**
     * <pre>
     * The name of the service associated with this Rollout.
     * </pre>
     *
     * <code>string service_name = 8;</code>
     */
    public function getServiceName()
    {
        return $this->service_name;
    }

    /**
     * <pre>
     * The name of the service associated with this Rollout.
     * </pre>
     *
     * <code>string service_name = 8;</code>
     */
    public function setServiceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->service_name = $var;
    }

    public function getStrategy()
    {
        return $this->whichOneof("strategy");
    }

}

