<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/protobuf/emptymessage.proto

namespace Google\Protobuf;

use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class EmptyMessage extends \Google\Protobuf\Internal\Message
{

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0ac5010a22676f6f676c652f70726f746f6275662f656d7074796d657373" .
    "6167652e70726f746f120f676f6f676c652e70726f746f627566220e0a0c" .
    "456d7074794d65737361676542760a13636f6d2e676f6f676c652e70726f" .
    "746f627566420a456d70747950726f746f50015a276769746875622e636f" .
    "6d2f676f6c616e672f70726f746f6275662f7074797065732f656d707479" .
    "f80101a20203475042aa021e476f6f676c652e50726f746f6275662e5765" .
    "6c6c4b6e6f776e5479706573620670726f746f33"
));

