<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/protobuf/field_mask.proto

namespace Google\Protobuf;

use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class FieldMask extends \Google\Protobuf\Internal\Message
{
    private $paths;

    public function getPaths()
    {
        return $this->paths;
    }

    public function setPaths(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::STRING);
        $this->paths = $var;
    }

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0aa7010a20676f6f676c652f70726f746f6275662f6669656c645f6d6173" .
    "6b2e70726f746f120f676f6f676c652e70726f746f627566221a0a094669" .
    "656c644d61736b120d0a057061746873180120032809424e0a13636f6d2e" .
    "676f6f676c652e70726f746f627566420e4669656c644d61736b50726f74" .
    "6f5001a20203475042aa021e476f6f676c652e50726f746f6275662e5765" .
    "6c6c4b6e6f776e5479706573620670726f746f33"
));

