<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/protobuf/source_context.proto

namespace Google\Protobuf;

use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class SourceContext extends \Google\Protobuf\Internal\Message
{
    private $file_name = '';

    public function getFileName()
    {
        return $this->file_name;
    }

    public function setFileName($var)
    {
        GPBUtil::checkString($var, True);
        $this->file_name = $var;
    }

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0ab7010a24676f6f676c652f70726f746f6275662f736f757263655f636f" .
    "6e746578742e70726f746f120f676f6f676c652e70726f746f6275662222" .
    "0a0d536f75726365436f6e7465787412110a0966696c655f6e616d651801" .
    "2001280942520a13636f6d2e676f6f676c652e70726f746f627566421253" .
    "6f75726365436f6e7465787450726f746f5001a20203475042aa021e476f" .
    "6f676c652e50726f746f6275662e57656c6c4b6e6f776e54797065736206" .
    "70726f746f33"
));

