<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/protobuf/type.proto

namespace Google\Protobuf;

require_once('google/protobuf/any.pb.php');
require_once('google/protobuf/source_context.pb.php');
use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class Type extends \Google\Protobuf\Internal\Message
{
    private $name = '';
    private $fields;
    private $oneofs;
    private $options;
    private $source_context = null;
    private $syntax = 0;

    public function getName()
    {
        return $this->name;
    }

    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

    public function getFields()
    {
        return $this->fields;
    }

    public function setFields(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Google\Protobuf\Field::class);
        $this->fields = $var;
    }

    public function getOneofs()
    {
        return $this->oneofs;
    }

    public function setOneofs(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::STRING);
        $this->oneofs = $var;
    }

    public function getOptions()
    {
        return $this->options;
    }

    public function setOptions(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Google\Protobuf\Option::class);
        $this->options = $var;
    }

    public function getSourceContext()
    {
        return $this->source_context;
    }

    public function setSourceContext(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\SourceContext::class);
        $this->source_context = $var;
    }

    public function getSyntax()
    {
        return $this->syntax;
    }

    public function setSyntax($var)
    {
        GPBUtil::checkEnum($var, \Google\Protobuf\Syntax::class);
        $this->syntax = $var;
    }

}

class Field extends \Google\Protobuf\Internal\Message
{
    private $kind = 0;
    private $cardinality = 0;
    private $number = 0;
    private $name = '';
    private $type_url = '';
    private $oneof_index = 0;
    private $packed = false;
    private $options;
    private $json_name = '';
    private $default_value = '';

    public function getKind()
    {
        return $this->kind;
    }

    public function setKind($var)
    {
        GPBUtil::checkEnum($var, \Google\Protobuf\Field_Kind::class);
        $this->kind = $var;
    }

    public function getCardinality()
    {
        return $this->cardinality;
    }

    public function setCardinality($var)
    {
        GPBUtil::checkEnum($var, \Google\Protobuf\Field_Cardinality::class);
        $this->cardinality = $var;
    }

    public function getNumber()
    {
        return $this->number;
    }

    public function setNumber($var)
    {
        GPBUtil::checkInt32($var);
        $this->number = $var;
    }

    public function getName()
    {
        return $this->name;
    }

    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

    public function getTypeUrl()
    {
        return $this->type_url;
    }

    public function setTypeUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->type_url = $var;
    }

    public function getOneofIndex()
    {
        return $this->oneof_index;
    }

    public function setOneofIndex($var)
    {
        GPBUtil::checkInt32($var);
        $this->oneof_index = $var;
    }

    public function getPacked()
    {
        return $this->packed;
    }

    public function setPacked($var)
    {
        GPBUtil::checkBool($var);
        $this->packed = $var;
    }

    public function getOptions()
    {
        return $this->options;
    }

    public function setOptions(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Google\Protobuf\Option::class);
        $this->options = $var;
    }

    public function getJsonName()
    {
        return $this->json_name;
    }

    public function setJsonName($var)
    {
        GPBUtil::checkString($var, True);
        $this->json_name = $var;
    }

    public function getDefaultValue()
    {
        return $this->default_value;
    }

    public function setDefaultValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->default_value = $var;
    }

}

class Field_Kind
{
    const TYPE_UNKNOWN = 0;
    const TYPE_DOUBLE = 1;
    const TYPE_FLOAT = 2;
    const TYPE_INT64 = 3;
    const TYPE_UINT64 = 4;
    const TYPE_INT32 = 5;
    const TYPE_FIXED64 = 6;
    const TYPE_FIXED32 = 7;
    const TYPE_BOOL = 8;
    const TYPE_STRING = 9;
    const TYPE_GROUP = 10;
    const TYPE_MESSAGE = 11;
    const TYPE_BYTES = 12;
    const TYPE_UINT32 = 13;
    const TYPE_ENUM = 14;
    const TYPE_SFIXED32 = 15;
    const TYPE_SFIXED64 = 16;
    const TYPE_SINT32 = 17;
    const TYPE_SINT64 = 18;
}

class Field_Cardinality
{
    const CARDINALITY_UNKNOWN = 0;
    const CARDINALITY_OPTIONAL = 1;
    const CARDINALITY_REQUIRED = 2;
    const CARDINALITY_REPEATED = 3;
}

class Enum extends \Google\Protobuf\Internal\Message
{
    private $name = '';
    private $enumvalue;
    private $options;
    private $source_context = null;
    private $syntax = 0;

    public function getName()
    {
        return $this->name;
    }

    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

    public function getEnumvalue()
    {
        return $this->enumvalue;
    }

    public function setEnumvalue(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Google\Protobuf\EnumValue::class);
        $this->enumvalue = $var;
    }

    public function getOptions()
    {
        return $this->options;
    }

    public function setOptions(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Google\Protobuf\Option::class);
        $this->options = $var;
    }

    public function getSourceContext()
    {
        return $this->source_context;
    }

    public function setSourceContext(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\SourceContext::class);
        $this->source_context = $var;
    }

    public function getSyntax()
    {
        return $this->syntax;
    }

    public function setSyntax($var)
    {
        GPBUtil::checkEnum($var, \Google\Protobuf\Syntax::class);
        $this->syntax = $var;
    }

}

class EnumValue extends \Google\Protobuf\Internal\Message
{
    private $name = '';
    private $number = 0;
    private $options;

    public function getName()
    {
        return $this->name;
    }

    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

    public function getNumber()
    {
        return $this->number;
    }

    public function setNumber($var)
    {
        GPBUtil::checkInt32($var);
        $this->number = $var;
    }

    public function getOptions()
    {
        return $this->options;
    }

    public function setOptions(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Google\Protobuf\Option::class);
        $this->options = $var;
    }

}

class Option extends \Google\Protobuf\Internal\Message
{
    private $name = '';
    private $value = null;

    public function getName()
    {
        return $this->name;
    }

    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

    public function getValue()
    {
        return $this->value;
    }

    public function setValue(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Any::class);
        $this->value = $var;
    }

}

class Syntax
{
    const SYNTAX_PROTO2 = 0;
    const SYNTAX_PROTO3 = 1;
}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0a890c0a1a676f6f676c652f70726f746f6275662f747970652e70726f74" .
    "6f120f676f6f676c652e70726f746f6275661a19676f6f676c652f70726f" .
    "746f6275662f616e792e70726f746f1a24676f6f676c652f70726f746f62" .
    "75662f736f757263655f636f6e746578742e70726f746f22d7010a045479" .
    "7065120c0a046e616d6518012001280912260a066669656c647318022003" .
    "280b32162e676f6f676c652e70726f746f6275662e4669656c64120e0a06" .
    "6f6e656f667318032003280912280a076f7074696f6e7318042003280b32" .
    "172e676f6f676c652e70726f746f6275662e4f7074696f6e12360a0e736f" .
    "757263655f636f6e7465787418052001280b321e2e676f6f676c652e7072" .
    "6f746f6275662e536f75726365436f6e7465787412270a0673796e746178" .
    "18062001280e32172e676f6f676c652e70726f746f6275662e53796e7461" .
    "7822d5050a054669656c6412290a046b696e6418012001280e321b2e676f" .
    "6f676c652e70726f746f6275662e4669656c642e4b696e6412370a0b6361" .
    "7264696e616c69747918022001280e32222e676f6f676c652e70726f746f" .
    "6275662e4669656c642e43617264696e616c697479120e0a066e756d6265" .
    "72180320012805120c0a046e616d6518042001280912100a08747970655f" .
    "75726c18062001280912130a0b6f6e656f665f696e646578180720012805" .
    "120e0a067061636b656418082001280812280a076f7074696f6e73180920" .
    "03280b32172e676f6f676c652e70726f746f6275662e4f7074696f6e1211" .
    "0a096a736f6e5f6e616d65180a2001280912150a0d64656661756c745f76" .
    "616c7565180b2001280922c8020a044b696e6412100a0c545950455f554e" .
    "4b4e4f574e1000120f0a0b545950455f444f55424c451001120e0a0a5459" .
    "50455f464c4f41541002120e0a0a545950455f494e5436341003120f0a0b" .
    "545950455f55494e5436341004120e0a0a545950455f494e543332100512" .
    "100a0c545950455f46495845443634100612100a0c545950455f46495845" .
    "4433321007120d0a09545950455f424f4f4c1008120f0a0b545950455f53" .
    "5452494e471009120e0a0a545950455f47524f5550100a12100a0c545950" .
    "455f4d455353414745100b120e0a0a545950455f4259544553100c120f0a" .
    "0b545950455f55494e543332100d120d0a09545950455f454e554d100e12" .
    "110a0d545950455f5346495845443332100f12110a0d545950455f534649" .
    "58454436341010120f0a0b545950455f53494e5433321011120f0a0b5459" .
    "50455f53494e543634101222740a0b43617264696e616c69747912170a13" .
    "43415244494e414c4954595f554e4b4e4f574e100012180a144341524449" .
    "4e414c4954595f4f5054494f4e414c100112180a1443415244494e414c49" .
    "54595f5245515549524544100212180a1443415244494e414c4954595f52" .
    "45504541544544100322ce010a04456e756d120c0a046e616d6518012001" .
    "2809122d0a09656e756d76616c756518022003280b321a2e676f6f676c65" .
    "2e70726f746f6275662e456e756d56616c756512280a076f7074696f6e73" .
    "18032003280b32172e676f6f676c652e70726f746f6275662e4f7074696f" .
    "6e12360a0e736f757263655f636f6e7465787418042001280b321e2e676f" .
    "6f676c652e70726f746f6275662e536f75726365436f6e7465787412270a" .
    "0673796e74617818052001280e32172e676f6f676c652e70726f746f6275" .
    "662e53796e74617822530a09456e756d56616c7565120c0a046e616d6518" .
    "0120012809120e0a066e756d62657218022001280512280a076f7074696f" .
    "6e7318032003280b32172e676f6f676c652e70726f746f6275662e4f7074" .
    "696f6e223b0a064f7074696f6e120c0a046e616d6518012001280912230a" .
    "0576616c756518022001280b32142e676f6f676c652e70726f746f627566" .
    "2e416e792a2e0a0653796e74617812110a0d53594e5441585f50524f544f" .
    "32100012110a0d53594e5441585f50524f544f331001424c0a13636f6d2e" .
    "676f6f676c652e70726f746f62756642095479706550726f746f5001f801" .
    "01a20203475042aa021e476f6f676c652e50726f746f6275662e57656c6c" .
    "4b6e6f776e5479706573620670726f746f33"
));

