<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/rpc/error_details.proto

namespace Google\Rpc;

require_once('google/protobuf/duration.pb.php');
use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class RetryInfo extends \Google\Protobuf\Internal\Message
{
    private $retry_delay = null;

    public function getRetryDelay()
    {
        return $this->retry_delay;
    }

    public function setRetryDelay(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Duration::class);
        $this->retry_delay = $var;
    }

}

class DebugInfo extends \Google\Protobuf\Internal\Message
{
    private $stack_entries;
    private $detail = '';

    public function getStackEntries()
    {
        return $this->stack_entries;
    }

    public function setStackEntries(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::STRING);
        $this->stack_entries = $var;
    }

    public function getDetail()
    {
        return $this->detail;
    }

    public function setDetail($var)
    {
        GPBUtil::checkString($var, True);
        $this->detail = $var;
    }

}

class QuotaFailure extends \Google\Protobuf\Internal\Message
{
    private $violations;

    public function getViolations()
    {
        return $this->violations;
    }

    public function setViolations(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Google\Rpc\QuotaFailure_Violation::class);
        $this->violations = $var;
    }

}

class QuotaFailure_Violation extends \Google\Protobuf\Internal\Message
{
    private $subject = '';
    private $description = '';

    public function getSubject()
    {
        return $this->subject;
    }

    public function setSubject($var)
    {
        GPBUtil::checkString($var, True);
        $this->subject = $var;
    }

    public function getDescription()
    {
        return $this->description;
    }

    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;
    }

}

class BadRequest extends \Google\Protobuf\Internal\Message
{
    private $field_violations;

    public function getFieldViolations()
    {
        return $this->field_violations;
    }

    public function setFieldViolations(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Google\Rpc\BadRequest_FieldViolation::class);
        $this->field_violations = $var;
    }

}

class BadRequest_FieldViolation extends \Google\Protobuf\Internal\Message
{
    private $field = '';
    private $description = '';

    public function getField()
    {
        return $this->field;
    }

    public function setField($var)
    {
        GPBUtil::checkString($var, True);
        $this->field = $var;
    }

    public function getDescription()
    {
        return $this->description;
    }

    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;
    }

}

class RequestInfo extends \Google\Protobuf\Internal\Message
{
    private $request_id = '';
    private $serving_data = '';

    public function getRequestId()
    {
        return $this->request_id;
    }

    public function setRequestId($var)
    {
        GPBUtil::checkString($var, True);
        $this->request_id = $var;
    }

    public function getServingData()
    {
        return $this->serving_data;
    }

    public function setServingData($var)
    {
        GPBUtil::checkString($var, True);
        $this->serving_data = $var;
    }

}

class ResourceInfo extends \Google\Protobuf\Internal\Message
{
    private $resource_type = '';
    private $resource_name = '';
    private $owner = '';
    private $description = '';

    public function getResourceType()
    {
        return $this->resource_type;
    }

    public function setResourceType($var)
    {
        GPBUtil::checkString($var, True);
        $this->resource_type = $var;
    }

    public function getResourceName()
    {
        return $this->resource_name;
    }

    public function setResourceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->resource_name = $var;
    }

    public function getOwner()
    {
        return $this->owner;
    }

    public function setOwner($var)
    {
        GPBUtil::checkString($var, True);
        $this->owner = $var;
    }

    public function getDescription()
    {
        return $this->description;
    }

    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;
    }

}

class Help extends \Google\Protobuf\Internal\Message
{
    private $links;

    public function getLinks()
    {
        return $this->links;
    }

    public function setLinks(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Google\Rpc\Help_Link::class);
        $this->links = $var;
    }

}

class Help_Link extends \Google\Protobuf\Internal\Message
{
    private $description = '';
    private $url = '';

    public function getDescription()
    {
        return $this->description;
    }

    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;
    }

    public function getUrl()
    {
        return $this->url;
    }

    public function setUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->url = $var;
    }

}

class LocalizedMessage extends \Google\Protobuf\Internal\Message
{
    private $locale = '';
    private $message = '';

    public function getLocale()
    {
        return $this->locale;
    }

    public function setLocale($var)
    {
        GPBUtil::checkString($var, True);
        $this->locale = $var;
    }

    public function getMessage()
    {
        return $this->message;
    }

    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;
    }

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0adc060a1e676f6f676c652f7270632f6572726f725f64657461696c732e" .
    "70726f746f120a676f6f676c652e7270631a1e676f6f676c652f70726f74" .
    "6f6275662f6475726174696f6e2e70726f746f223b0a095265747279496e" .
    "666f122e0a0b72657472795f64656c617918012001280b32192e676f6f67" .
    "6c652e70726f746f6275662e4475726174696f6e22320a09446562756749" .
    "6e666f12150a0d737461636b5f656e7472696573180120032809120e0a06" .
    "64657461696c18022001280922790a0c51756f74614661696c7572651236" .
    "0a0a76696f6c6174696f6e7318012003280b32222e676f6f676c652e7270" .
    "632e51756f74614661696c7572652e56696f6c6174696f6e1a310a095669" .
    "6f6c6174696f6e120f0a077375626a65637418012001280912130a0b6465" .
    "736372697074696f6e1802200128092283010a0a42616452657175657374" .
    "123f0a106669656c645f76696f6c6174696f6e7318012003280b32252e67" .
    "6f6f676c652e7270632e426164526571756573742e4669656c6456696f6c" .
    "6174696f6e1a340a0e4669656c6456696f6c6174696f6e120d0a05666965" .
    "6c6418012001280912130a0b6465736372697074696f6e18022001280922" .
    "370a0b52657175657374496e666f12120a0a726571756573745f69641801" .
    "2001280912140a0c73657276696e675f6461746118022001280922600a0c" .
    "5265736f75726365496e666f12150a0d7265736f757263655f7479706518" .
    "012001280912150a0d7265736f757263655f6e616d65180220012809120d" .
    "0a056f776e657218032001280912130a0b6465736372697074696f6e1804" .
    "2001280922560a0448656c7012240a056c696e6b7318012003280b32152e" .
    "676f6f676c652e7270632e48656c702e4c696e6b1a280a044c696e6b1213" .
    "0a0b6465736372697074696f6e180120012809120b0a0375726c18022001" .
    "280922330a104c6f63616c697a65644d657373616765120e0a066c6f6361" .
    "6c65180120012809120f0a076d657373616765180220012809426c0a0e63" .
    "6f6d2e676f6f676c652e72706342114572726f7244657461696c7350726f" .
    "746f50015a3f676f6f676c652e676f6c616e672e6f72672f67656e70726f" .
    "746f2f676f6f676c65617069732f7270632f65727264657461696c733b65" .
    "727264657461696c73a20203525043620670726f746f33"
));

