<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/rpc/status.proto

namespace Google\Rpc;

require_once('google/protobuf/any.pb.php');
use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class Status extends \Google\Protobuf\Internal\Message
{
    private $code = 0;
    private $message = '';
    private $details;

    public function getCode()
    {
        return $this->code;
    }

    public function setCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->code = $var;
    }

    public function getMessage()
    {
        return $this->message;
    }

    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;
    }

    public function getDetails()
    {
        return $this->details;
    }

    public function setDetails(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Google\Protobuf\Any::class);
        $this->details = $var;
    }

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0af8010a17676f6f676c652f7270632f7374617475732e70726f746f120a" .
    "676f6f676c652e7270631a19676f6f676c652f70726f746f6275662f616e" .
    "792e70726f746f224e0a06537461747573120c0a04636f64651801200128" .
    "05120f0a076d65737361676518022001280912250a0764657461696c7318" .
    "032003280b32142e676f6f676c652e70726f746f6275662e416e79425e0a" .
    "0e636f6d2e676f6f676c652e727063420b53746174757350726f746f5001" .
    "5a37676f6f676c652e676f6c616e672e6f72672f67656e70726f746f2f67" .
    "6f6f676c65617069732f7270632f7374617475733b737461747573a20203" .
    "525043620670726f746f33"
));

