<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/monitored_resource.proto

namespace GPBMetadata\Google\Api;

class MonitoredResource
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Label::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aee030a23676f6f676c652f6170692f6d6f6e69746f7265645f7265736f" .
            "757263652e70726f746f120a676f6f676c652e6170691a16676f6f676c65" .
            "2f6170692f6c6162656c2e70726f746f2291010a1b4d6f6e69746f726564" .
            "5265736f7572636544657363726970746f72120c0a046e616d6518052001" .
            "2809120c0a047479706518012001280912140a0c646973706c61795f6e61" .
            "6d6518022001280912130a0b6465736372697074696f6e18032001280912" .
            "2b0a066c6162656c7318042003280b321b2e676f6f676c652e6170692e4c" .
            "6162656c44657363726970746f72228b010a114d6f6e69746f7265645265" .
            "736f75726365120c0a047479706518012001280912390a066c6162656c73" .
            "18022003280b32292e676f6f676c652e6170692e4d6f6e69746f72656452" .
            "65736f757263652e4c6162656c73456e7472791a2d0a0b4c6162656c7345" .
            "6e747279120b0a036b6579180120012809120d0a0576616c756518022001" .
            "28093a02380142790a0e636f6d2e676f6f676c652e61706942164d6f6e69" .
            "746f7265645265736f7572636550726f746f50015a43676f6f676c652e67" .
            "6f6c616e672e6f72672f67656e70726f746f2f676f6f676c65617069732f" .
            "6170692f6d6f6e69746f7265647265733b6d6f6e69746f726564726573f8" .
            "0101a2020447415049620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

