<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/source_info.proto

namespace GPBMetadata\Google\Api;

class SourceInfo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Any::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0afa010a1c676f6f676c652f6170692f736f757263655f696e666f2e7072" .
            "6f746f120a676f6f676c652e6170691a19676f6f676c652f70726f746f62" .
            "75662f616e792e70726f746f22380a0a536f75726365496e666f122a0a0c" .
            "736f757263655f66696c657318012003280b32142e676f6f676c652e7072" .
            "6f746f6275662e416e7942710a0e636f6d2e676f6f676c652e617069420f" .
            "536f75726365496e666f50726f746f50015a45676f6f676c652e676f6c61" .
            "6e672e6f72672f67656e70726f746f2f676f6f676c65617069732f617069" .
            "2f73657276696365636f6e6669673b73657276696365636f6e666967a202" .
            "0447415049620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

