<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/language/v1/language_service.proto

namespace Google\Cloud\Language\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Represents a mention for an entity in the text. Currently, proper noun
 * mentions are supported.
 * </pre>
 *
 * Protobuf type <code>google.cloud.language.v1.EntityMention</code>
 */
class EntityMention extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The mention text.
     * </pre>
     *
     * <code>.google.cloud.language.v1.TextSpan text = 1;</code>
     */
    private $text = null;
    /**
     * <pre>
     * The type of the entity mention.
     * </pre>
     *
     * <code>.google.cloud.language.v1.EntityMention.Type type = 2;</code>
     */
    private $type = 0;

    public function __construct() {
        \GPBMetadata\Google\Cloud\Language\V1\LanguageService::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The mention text.
     * </pre>
     *
     * <code>.google.cloud.language.v1.TextSpan text = 1;</code>
     */
    public function getText()
    {
        return $this->text;
    }

    /**
     * <pre>
     * The mention text.
     * </pre>
     *
     * <code>.google.cloud.language.v1.TextSpan text = 1;</code>
     */
    public function setText(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Cloud\Language\V1\TextSpan::class);
        $this->text = $var;
    }

    /**
     * <pre>
     * The type of the entity mention.
     * </pre>
     *
     * <code>.google.cloud.language.v1.EntityMention.Type type = 2;</code>
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * <pre>
     * The type of the entity mention.
     * </pre>
     *
     * <code>.google.cloud.language.v1.EntityMention.Type type = 2;</code>
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Google\Cloud\Language\V1\EntityMention_Type::class);
        $this->type = $var;
    }

}

