<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/privacy/dlp/v2beta1/storage.proto

namespace Google\Privacy\Dlp\V2beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Record key for a finding in Cloud Datastore.
 * </pre>
 *
 * Protobuf type <code>google.privacy.dlp.v2beta1.DatastoreKey</code>
 */
class DatastoreKey extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * Datastore entity key.
     * </pre>
     *
     * <code>.google.privacy.dlp.v2beta1.Key entity_key = 1;</code>
     */
    private $entity_key = null;

    public function __construct() {
        \GPBMetadata\Google\Privacy\Dlp\V2Beta1\Storage::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Datastore entity key.
     * </pre>
     *
     * <code>.google.privacy.dlp.v2beta1.Key entity_key = 1;</code>
     */
    public function getEntityKey()
    {
        return $this->entity_key;
    }

    /**
     * <pre>
     * Datastore entity key.
     * </pre>
     *
     * <code>.google.privacy.dlp.v2beta1.Key entity_key = 1;</code>
     */
    public function setEntityKey(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Privacy\Dlp\V2beta1\Key::class);
        $this->entity_key = $var;
    }

}

