<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/privacy/dlp/v2beta1/storage.proto

namespace Google\Privacy\Dlp\V2beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * General identifier of a data field in a storage service.
 * </pre>
 *
 * Protobuf type <code>google.privacy.dlp.v2beta1.FieldId</code>
 */
class FieldId extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * Column name describing the field.
     * </pre>
     *
     * <code>string column_name = 1;</code>
     */
    private $column_name = '';

    public function __construct() {
        \GPBMetadata\Google\Privacy\Dlp\V2Beta1\Storage::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Column name describing the field.
     * </pre>
     *
     * <code>string column_name = 1;</code>
     */
    public function getColumnName()
    {
        return $this->column_name;
    }

    /**
     * <pre>
     * Column name describing the field.
     * </pre>
     *
     * <code>string column_name = 1;</code>
     */
    public function setColumnName($var)
    {
        GPBUtil::checkString($var, True);
        $this->column_name = $var;
    }

}

