<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/privacy/dlp/v2beta1/dlp.proto

namespace Google\Privacy\Dlp\V2beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Info type description.
 * </pre>
 *
 * Protobuf type <code>google.privacy.dlp.v2beta1.InfoTypeDescription</code>
 */
class InfoTypeDescription extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * Internal name of the info type.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    private $name = '';
    /**
     * <pre>
     * Human readable form of the info type name.
     * </pre>
     *
     * <code>string display_name = 2;</code>
     */
    private $display_name = '';
    /**
     * <pre>
     * List of categories this info type belongs to.
     * </pre>
     *
     * <code>repeated .google.privacy.dlp.v2beta1.CategoryDescription categories = 3;</code>
     */
    private $categories;

    public function __construct() {
        \GPBMetadata\Google\Privacy\Dlp\V2Beta1\Dlp::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Internal name of the info type.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * <pre>
     * Internal name of the info type.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

    /**
     * <pre>
     * Human readable form of the info type name.
     * </pre>
     *
     * <code>string display_name = 2;</code>
     */
    public function getDisplayName()
    {
        return $this->display_name;
    }

    /**
     * <pre>
     * Human readable form of the info type name.
     * </pre>
     *
     * <code>string display_name = 2;</code>
     */
    public function setDisplayName($var)
    {
        GPBUtil::checkString($var, True);
        $this->display_name = $var;
    }

    /**
     * <pre>
     * List of categories this info type belongs to.
     * </pre>
     *
     * <code>repeated .google.privacy.dlp.v2beta1.CategoryDescription categories = 3;</code>
     */
    public function getCategories()
    {
        return $this->categories;
    }

    /**
     * <pre>
     * List of categories this info type belongs to.
     * </pre>
     *
     * <code>repeated .google.privacy.dlp.v2beta1.CategoryDescription categories = 3;</code>
     */
    public function setCategories(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Privacy\Dlp\V2beta1\CategoryDescription::class);
        $this->categories = $var;
    }

}

