<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/privacy/dlp/v2beta1/dlp.proto

namespace Google\Privacy\Dlp\V2beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Stats regarding a specific InfoType.
 * </pre>
 *
 * Protobuf type <code>google.privacy.dlp.v2beta1.InfoTypeStatistics</code>
 */
class InfoTypeStatistics extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The type of finding this stat is for.
     * </pre>
     *
     * <code>.google.privacy.dlp.v2beta1.InfoType info_type = 1;</code>
     */
    private $info_type = null;
    /**
     * <pre>
     * Number of findings for this info type.
     * </pre>
     *
     * <code>int64 count = 2;</code>
     */
    private $count = 0;

    public function __construct() {
        \GPBMetadata\Google\Privacy\Dlp\V2Beta1\Dlp::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The type of finding this stat is for.
     * </pre>
     *
     * <code>.google.privacy.dlp.v2beta1.InfoType info_type = 1;</code>
     */
    public function getInfoType()
    {
        return $this->info_type;
    }

    /**
     * <pre>
     * The type of finding this stat is for.
     * </pre>
     *
     * <code>.google.privacy.dlp.v2beta1.InfoType info_type = 1;</code>
     */
    public function setInfoType(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Privacy\Dlp\V2beta1\InfoType::class);
        $this->info_type = $var;
    }

    /**
     * <pre>
     * Number of findings for this info type.
     * </pre>
     *
     * <code>int64 count = 2;</code>
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * <pre>
     * Number of findings for this info type.
     * </pre>
     *
     * <code>int64 count = 2;</code>
     */
    public function setCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->count = $var;
    }

}

