<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/privacy/dlp/v2beta1/dlp.proto

namespace Google\Privacy\Dlp\V2beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * All the findings for a single scanned item.
 * </pre>
 *
 * Protobuf type <code>google.privacy.dlp.v2beta1.InspectResult</code>
 */
class InspectResult extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * List of findings for an item.
     * </pre>
     *
     * <code>repeated .google.privacy.dlp.v2beta1.Finding findings = 1;</code>
     */
    private $findings;
    /**
     * <pre>
     * If true, then this item might have more findings than were returned,
     * and the findings returned are an arbitrary subset of all findings.
     * The findings list might be truncated because the input items were too
     * large, or because the server reached the maximum amount of resources
     * allowed for a single API call. For best results, divide the input into
     * smaller batches.
     * </pre>
     *
     * <code>bool findings_truncated = 2;</code>
     */
    private $findings_truncated = false;

    public function __construct() {
        \GPBMetadata\Google\Privacy\Dlp\V2Beta1\Dlp::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * List of findings for an item.
     * </pre>
     *
     * <code>repeated .google.privacy.dlp.v2beta1.Finding findings = 1;</code>
     */
    public function getFindings()
    {
        return $this->findings;
    }

    /**
     * <pre>
     * List of findings for an item.
     * </pre>
     *
     * <code>repeated .google.privacy.dlp.v2beta1.Finding findings = 1;</code>
     */
    public function setFindings(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Privacy\Dlp\V2beta1\Finding::class);
        $this->findings = $arr;
    }

    /**
     * <pre>
     * If true, then this item might have more findings than were returned,
     * and the findings returned are an arbitrary subset of all findings.
     * The findings list might be truncated because the input items were too
     * large, or because the server reached the maximum amount of resources
     * allowed for a single API call. For best results, divide the input into
     * smaller batches.
     * </pre>
     *
     * <code>bool findings_truncated = 2;</code>
     */
    public function getFindingsTruncated()
    {
        return $this->findings_truncated;
    }

    /**
     * <pre>
     * If true, then this item might have more findings than were returned,
     * and the findings returned are an arbitrary subset of all findings.
     * The findings list might be truncated because the input items were too
     * large, or because the server reached the maximum amount of resources
     * allowed for a single API call. For best results, divide the input into
     * smaller batches.
     * </pre>
     *
     * <code>bool findings_truncated = 2;</code>
     */
    public function setFindingsTruncated($var)
    {
        GPBUtil::checkBool($var);
        $this->findings_truncated = $var;
    }

}

