<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/privacy/dlp/v2beta1/dlp.proto

namespace Google\Privacy\Dlp\V2beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Metadata returned within GetOperation for an inspect request.
 * </pre>
 *
 * Protobuf type <code>google.privacy.dlp.v2beta1.InspectOperationMetadata</code>
 */
class InspectOperationMetadata extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * Total size in bytes that were processed.
     * </pre>
     *
     * <code>int64 processed_bytes = 1;</code>
     */
    private $processed_bytes = 0;
    /**
     * <pre>
     * Estimate of the number of bytes to process.
     * </pre>
     *
     * <code>int64 total_estimated_bytes = 4;</code>
     */
    private $total_estimated_bytes = 0;
    /**
     * <code>repeated .google.privacy.dlp.v2beta1.InfoTypeStatistics info_type_stats = 2;</code>
     */
    private $info_type_stats;
    /**
     * <pre>
     * The time which this request was started.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp create_time = 3;</code>
     */
    private $create_time = null;
    /**
     * <pre>
     * The inspect config used to create the Operation.
     * </pre>
     *
     * <code>.google.privacy.dlp.v2beta1.InspectConfig request_inspect_config = 5;</code>
     */
    private $request_inspect_config = null;
    /**
     * <pre>
     * The storage config used to create the Operation.
     * </pre>
     *
     * <code>.google.privacy.dlp.v2beta1.StorageConfig request_storage_config = 6;</code>
     */
    private $request_storage_config = null;
    /**
     * <pre>
     * Optional location to store findings.
     * </pre>
     *
     * <code>.google.privacy.dlp.v2beta1.OutputStorageConfig request_output_config = 7;</code>
     */
    private $request_output_config = null;

    public function __construct() {
        \GPBMetadata\Google\Privacy\Dlp\V2Beta1\Dlp::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Total size in bytes that were processed.
     * </pre>
     *
     * <code>int64 processed_bytes = 1;</code>
     */
    public function getProcessedBytes()
    {
        return $this->processed_bytes;
    }

    /**
     * <pre>
     * Total size in bytes that were processed.
     * </pre>
     *
     * <code>int64 processed_bytes = 1;</code>
     */
    public function setProcessedBytes($var)
    {
        GPBUtil::checkInt64($var);
        $this->processed_bytes = $var;
    }

    /**
     * <pre>
     * Estimate of the number of bytes to process.
     * </pre>
     *
     * <code>int64 total_estimated_bytes = 4;</code>
     */
    public function getTotalEstimatedBytes()
    {
        return $this->total_estimated_bytes;
    }

    /**
     * <pre>
     * Estimate of the number of bytes to process.
     * </pre>
     *
     * <code>int64 total_estimated_bytes = 4;</code>
     */
    public function setTotalEstimatedBytes($var)
    {
        GPBUtil::checkInt64($var);
        $this->total_estimated_bytes = $var;
    }

    /**
     * <code>repeated .google.privacy.dlp.v2beta1.InfoTypeStatistics info_type_stats = 2;</code>
     */
    public function getInfoTypeStats()
    {
        return $this->info_type_stats;
    }

    /**
     * <code>repeated .google.privacy.dlp.v2beta1.InfoTypeStatistics info_type_stats = 2;</code>
     */
    public function setInfoTypeStats(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Privacy\Dlp\V2beta1\InfoTypeStatistics::class);
        $this->info_type_stats = $var;
    }

    /**
     * <pre>
     * The time which this request was started.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp create_time = 3;</code>
     */
    public function getCreateTime()
    {
        return $this->create_time;
    }

    /**
     * <pre>
     * The time which this request was started.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp create_time = 3;</code>
     */
    public function setCreateTime(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->create_time = $var;
    }

    /**
     * <pre>
     * The inspect config used to create the Operation.
     * </pre>
     *
     * <code>.google.privacy.dlp.v2beta1.InspectConfig request_inspect_config = 5;</code>
     */
    public function getRequestInspectConfig()
    {
        return $this->request_inspect_config;
    }

    /**
     * <pre>
     * The inspect config used to create the Operation.
     * </pre>
     *
     * <code>.google.privacy.dlp.v2beta1.InspectConfig request_inspect_config = 5;</code>
     */
    public function setRequestInspectConfig(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Privacy\Dlp\V2beta1\InspectConfig::class);
        $this->request_inspect_config = $var;
    }

    /**
     * <pre>
     * The storage config used to create the Operation.
     * </pre>
     *
     * <code>.google.privacy.dlp.v2beta1.StorageConfig request_storage_config = 6;</code>
     */
    public function getRequestStorageConfig()
    {
        return $this->request_storage_config;
    }

    /**
     * <pre>
     * The storage config used to create the Operation.
     * </pre>
     *
     * <code>.google.privacy.dlp.v2beta1.StorageConfig request_storage_config = 6;</code>
     */
    public function setRequestStorageConfig(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Privacy\Dlp\V2beta1\StorageConfig::class);
        $this->request_storage_config = $var;
    }

    /**
     * <pre>
     * Optional location to store findings.
     * </pre>
     *
     * <code>.google.privacy.dlp.v2beta1.OutputStorageConfig request_output_config = 7;</code>
     */
    public function getRequestOutputConfig()
    {
        return $this->request_output_config;
    }

    /**
     * <pre>
     * Optional location to store findings.
     * </pre>
     *
     * <code>.google.privacy.dlp.v2beta1.OutputStorageConfig request_output_config = 7;</code>
     */
    public function setRequestOutputConfig(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Privacy\Dlp\V2beta1\OutputStorageConfig::class);
        $this->request_output_config = $var;
    }

}

