<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/privacy/dlp/v2beta1/dlp.proto

namespace Google\Privacy\Dlp\V2beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Request for the list of results in a given inspect operation.
 * </pre>
 *
 * Protobuf type <code>google.privacy.dlp.v2beta1.ListInspectFindingsRequest</code>
 */
class ListInspectFindingsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * Identifier of the results set returned as metadata of
     * the longrunning operation created by a call to CreateInspectOperation.
     * Should be in the format of `inspect/results/{id}.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    private $name = '';
    /**
     * <pre>
     * Maximum number of results to return.
     * If 0, the implementation will select a reasonable value.
     * </pre>
     *
     * <code>int32 page_size = 2;</code>
     */
    private $page_size = 0;
    /**
     * <pre>
     * The value returned by the last `ListInspectFindingsResponse`; indicates
     * that this is a continuation of a prior `ListInspectFindings` call, and that
     * the system should return the next page of data.
     * </pre>
     *
     * <code>string page_token = 3;</code>
     */
    private $page_token = '';

    public function __construct() {
        \GPBMetadata\Google\Privacy\Dlp\V2Beta1\Dlp::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Identifier of the results set returned as metadata of
     * the longrunning operation created by a call to CreateInspectOperation.
     * Should be in the format of `inspect/results/{id}.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * <pre>
     * Identifier of the results set returned as metadata of
     * the longrunning operation created by a call to CreateInspectOperation.
     * Should be in the format of `inspect/results/{id}.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

    /**
     * <pre>
     * Maximum number of results to return.
     * If 0, the implementation will select a reasonable value.
     * </pre>
     *
     * <code>int32 page_size = 2;</code>
     */
    public function getPageSize()
    {
        return $this->page_size;
    }

    /**
     * <pre>
     * Maximum number of results to return.
     * If 0, the implementation will select a reasonable value.
     * </pre>
     *
     * <code>int32 page_size = 2;</code>
     */
    public function setPageSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->page_size = $var;
    }

    /**
     * <pre>
     * The value returned by the last `ListInspectFindingsResponse`; indicates
     * that this is a continuation of a prior `ListInspectFindings` call, and that
     * the system should return the next page of data.
     * </pre>
     *
     * <code>string page_token = 3;</code>
     */
    public function getPageToken()
    {
        return $this->page_token;
    }

    /**
     * <pre>
     * The value returned by the last `ListInspectFindingsResponse`; indicates
     * that this is a continuation of a prior `ListInspectFindings` call, and that
     * the system should return the next page of data.
     * </pre>
     *
     * <code>string page_token = 3;</code>
     */
    public function setPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->page_token = $var;
    }

}

