<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/privacy/dlp/v2beta1/dlp.proto

namespace Google\Privacy\Dlp\V2beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Response to the ListInfoTypes request.
 * </pre>
 *
 * Protobuf type <code>google.privacy.dlp.v2beta1.ListInfoTypesResponse</code>
 */
class ListInfoTypesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * Set of sensitive info types belonging to a category.
     * </pre>
     *
     * <code>repeated .google.privacy.dlp.v2beta1.InfoTypeDescription info_types = 1;</code>
     */
    private $info_types;

    public function __construct() {
        \GPBMetadata\Google\Privacy\Dlp\V2Beta1\Dlp::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Set of sensitive info types belonging to a category.
     * </pre>
     *
     * <code>repeated .google.privacy.dlp.v2beta1.InfoTypeDescription info_types = 1;</code>
     */
    public function getInfoTypes()
    {
        return $this->info_types;
    }

    /**
     * <pre>
     * Set of sensitive info types belonging to a category.
     * </pre>
     *
     * <code>repeated .google.privacy.dlp.v2beta1.InfoTypeDescription info_types = 1;</code>
     */
    public function setInfoTypes(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Privacy\Dlp\V2beta1\InfoTypeDescription::class);
        $this->info_types = $arr;
    }

}

