<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/privacy/dlp/v2beta1/dlp.proto

namespace Google\Privacy\Dlp\V2beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Request for root categories of Info Types supported by the API.
 * Example values might include "FINANCE", "HEALTH", "FAST", "DEFAULT".
 * </pre>
 *
 * Protobuf type <code>google.privacy.dlp.v2beta1.ListRootCategoriesRequest</code>
 */
class ListRootCategoriesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * Optional language code for localized friendly category names.
     * If omitted or if localized strings are not available,
     * en-US strings will be returned.
     * </pre>
     *
     * <code>string language_code = 1;</code>
     */
    private $language_code = '';

    public function __construct() {
        \GPBMetadata\Google\Privacy\Dlp\V2Beta1\Dlp::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Optional language code for localized friendly category names.
     * If omitted or if localized strings are not available,
     * en-US strings will be returned.
     * </pre>
     *
     * <code>string language_code = 1;</code>
     */
    public function getLanguageCode()
    {
        return $this->language_code;
    }

    /**
     * <pre>
     * Optional language code for localized friendly category names.
     * If omitted or if localized strings are not available,
     * en-US strings will be returned.
     * </pre>
     *
     * <code>string language_code = 1;</code>
     */
    public function setLanguageCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->language_code = $var;
    }

}

