<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/privacy/dlp/v2beta1/dlp.proto

namespace Google\Privacy\Dlp\V2beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Response to the ListInspectFindings request.
 * </pre>
 *
 * Protobuf type <code>google.privacy.dlp.v2beta1.ListInspectFindingsResponse</code>
 */
class ListInspectFindingsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The results.
     * </pre>
     *
     * <code>.google.privacy.dlp.v2beta1.InspectResult result = 1;</code>
     */
    private $result = null;
    /**
     * <pre>
     * If not empty, indicates that there may be more results that match the
     * request; this value should be passed in a new `ListInspectFindingsRequest`.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     */
    private $next_page_token = '';

    public function __construct() {
        \GPBMetadata\Google\Privacy\Dlp\V2Beta1\Dlp::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The results.
     * </pre>
     *
     * <code>.google.privacy.dlp.v2beta1.InspectResult result = 1;</code>
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * <pre>
     * The results.
     * </pre>
     *
     * <code>.google.privacy.dlp.v2beta1.InspectResult result = 1;</code>
     */
    public function setResult(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Privacy\Dlp\V2beta1\InspectResult::class);
        $this->result = $var;
    }

    /**
     * <pre>
     * If not empty, indicates that there may be more results that match the
     * request; this value should be passed in a new `ListInspectFindingsRequest`.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     */
    public function getNextPageToken()
    {
        return $this->next_page_token;
    }

    /**
     * <pre>
     * If not empty, indicates that there may be more results that match the
     * request; this value should be passed in a new `ListInspectFindingsRequest`.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     */
    public function setNextPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->next_page_token = $var;
    }

}

