<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/privacy/dlp/v2beta1/dlp.proto

namespace Google\Privacy\Dlp\V2beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Specifies the location of a finding within its source item.
 * </pre>
 *
 * Protobuf type <code>google.privacy.dlp.v2beta1.Location</code>
 */
class Location extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * Zero-based byte offsets within a content item.
     * </pre>
     *
     * <code>.google.privacy.dlp.v2beta1.Range byte_range = 1;</code>
     */
    private $byte_range = null;
    /**
     * <pre>
     * Character offsets within a content item, included when content type
     * is a text. Default charset assumed to be UTF-8.
     * </pre>
     *
     * <code>.google.privacy.dlp.v2beta1.Range codepoint_range = 2;</code>
     */
    private $codepoint_range = null;
    /**
     * <pre>
     * Location within an image's pixels.
     * </pre>
     *
     * <code>repeated .google.privacy.dlp.v2beta1.ImageLocation image_boxes = 3;</code>
     */
    private $image_boxes;
    /**
     * <pre>
     * Key of the finding.
     * </pre>
     *
     * <code>.google.privacy.dlp.v2beta1.RecordKey record_key = 4;</code>
     */
    private $record_key = null;
    /**
     * <pre>
     * Field id of the field containing the finding.
     * </pre>
     *
     * <code>.google.privacy.dlp.v2beta1.FieldId field_id = 5;</code>
     */
    private $field_id = null;

    public function __construct() {
        \GPBMetadata\Google\Privacy\Dlp\V2Beta1\Dlp::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Zero-based byte offsets within a content item.
     * </pre>
     *
     * <code>.google.privacy.dlp.v2beta1.Range byte_range = 1;</code>
     */
    public function getByteRange()
    {
        return $this->byte_range;
    }

    /**
     * <pre>
     * Zero-based byte offsets within a content item.
     * </pre>
     *
     * <code>.google.privacy.dlp.v2beta1.Range byte_range = 1;</code>
     */
    public function setByteRange(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Privacy\Dlp\V2beta1\Range::class);
        $this->byte_range = $var;
    }

    /**
     * <pre>
     * Character offsets within a content item, included when content type
     * is a text. Default charset assumed to be UTF-8.
     * </pre>
     *
     * <code>.google.privacy.dlp.v2beta1.Range codepoint_range = 2;</code>
     */
    public function getCodepointRange()
    {
        return $this->codepoint_range;
    }

    /**
     * <pre>
     * Character offsets within a content item, included when content type
     * is a text. Default charset assumed to be UTF-8.
     * </pre>
     *
     * <code>.google.privacy.dlp.v2beta1.Range codepoint_range = 2;</code>
     */
    public function setCodepointRange(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Privacy\Dlp\V2beta1\Range::class);
        $this->codepoint_range = $var;
    }

    /**
     * <pre>
     * Location within an image's pixels.
     * </pre>
     *
     * <code>repeated .google.privacy.dlp.v2beta1.ImageLocation image_boxes = 3;</code>
     */
    public function getImageBoxes()
    {
        return $this->image_boxes;
    }

    /**
     * <pre>
     * Location within an image's pixels.
     * </pre>
     *
     * <code>repeated .google.privacy.dlp.v2beta1.ImageLocation image_boxes = 3;</code>
     */
    public function setImageBoxes(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Privacy\Dlp\V2beta1\ImageLocation::class);
        $this->image_boxes = $var;
    }

    /**
     * <pre>
     * Key of the finding.
     * </pre>
     *
     * <code>.google.privacy.dlp.v2beta1.RecordKey record_key = 4;</code>
     */
    public function getRecordKey()
    {
        return $this->record_key;
    }

    /**
     * <pre>
     * Key of the finding.
     * </pre>
     *
     * <code>.google.privacy.dlp.v2beta1.RecordKey record_key = 4;</code>
     */
    public function setRecordKey(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Privacy\Dlp\V2beta1\RecordKey::class);
        $this->record_key = $var;
    }

    /**
     * <pre>
     * Field id of the field containing the finding.
     * </pre>
     *
     * <code>.google.privacy.dlp.v2beta1.FieldId field_id = 5;</code>
     */
    public function getFieldId()
    {
        return $this->field_id;
    }

    /**
     * <pre>
     * Field id of the field containing the finding.
     * </pre>
     *
     * <code>.google.privacy.dlp.v2beta1.FieldId field_id = 5;</code>
     */
    public function setFieldId(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Privacy\Dlp\V2beta1\FieldId::class);
        $this->field_id = $var;
    }

}

