<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/privacy/dlp/v2beta1/dlp.proto

namespace Google\Privacy\Dlp\V2beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Generic half-open interval [start, end)
 * </pre>
 *
 * Protobuf type <code>google.privacy.dlp.v2beta1.Range</code>
 */
class Range extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * Index of the first character of the range (inclusive).
     * </pre>
     *
     * <code>int64 start = 1;</code>
     */
    private $start = 0;
    /**
     * <pre>
     * Index of the last character of the range (exclusive).
     * </pre>
     *
     * <code>int64 end = 2;</code>
     */
    private $end = 0;

    public function __construct() {
        \GPBMetadata\Google\Privacy\Dlp\V2Beta1\Dlp::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Index of the first character of the range (inclusive).
     * </pre>
     *
     * <code>int64 start = 1;</code>
     */
    public function getStart()
    {
        return $this->start;
    }

    /**
     * <pre>
     * Index of the first character of the range (inclusive).
     * </pre>
     *
     * <code>int64 start = 1;</code>
     */
    public function setStart($var)
    {
        GPBUtil::checkInt64($var);
        $this->start = $var;
    }

    /**
     * <pre>
     * Index of the last character of the range (exclusive).
     * </pre>
     *
     * <code>int64 end = 2;</code>
     */
    public function getEnd()
    {
        return $this->end;
    }

    /**
     * <pre>
     * Index of the last character of the range (exclusive).
     * </pre>
     *
     * <code>int64 end = 2;</code>
     */
    public function setEnd($var)
    {
        GPBUtil::checkInt64($var);
        $this->end = $var;
    }

}

