<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/privacy/dlp/v2beta1/storage.proto

namespace Google\Privacy\Dlp\V2beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Message for a unique key indicating a record that contains a finding.
 * </pre>
 *
 * Protobuf type <code>google.privacy.dlp.v2beta1.RecordKey</code>
 */
class RecordKey extends \Google\Protobuf\Internal\Message
{
    protected $type;

    public function __construct() {
        \GPBMetadata\Google\Privacy\Dlp\V2Beta1\Storage::initOnce();
        parent::__construct();
    }

    /**
     * <code>.google.privacy.dlp.v2beta1.CloudStorageKey cloud_storage_key = 1;</code>
     */
    public function getCloudStorageKey()
    {
        return $this->readOneof(1);
    }

    /**
     * <code>.google.privacy.dlp.v2beta1.CloudStorageKey cloud_storage_key = 1;</code>
     */
    public function setCloudStorageKey(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Privacy\Dlp\V2beta1\CloudStorageKey::class);
        $this->writeOneof(1, $var);
    }

    /**
     * <code>.google.privacy.dlp.v2beta1.DatastoreKey datastore_key = 2;</code>
     */
    public function getDatastoreKey()
    {
        return $this->readOneof(2);
    }

    /**
     * <code>.google.privacy.dlp.v2beta1.DatastoreKey datastore_key = 2;</code>
     */
    public function setDatastoreKey(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Privacy\Dlp\V2beta1\DatastoreKey::class);
        $this->writeOneof(2, $var);
    }

    public function getType()
    {
        return $this->whichOneof("type");
    }

}

