<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/privacy/dlp/v2beta1/dlp.proto

namespace Google\Privacy\Dlp\V2beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Results of deidentifying a list of items.
 * </pre>
 *
 * Protobuf type <code>google.privacy.dlp.v2beta1.RedactContentResponse</code>
 */
class RedactContentResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The redacted content.
     * </pre>
     *
     * <code>repeated .google.privacy.dlp.v2beta1.ContentItem items = 1;</code>
     */
    private $items;

    public function __construct() {
        \GPBMetadata\Google\Privacy\Dlp\V2Beta1\Dlp::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The redacted content.
     * </pre>
     *
     * <code>repeated .google.privacy.dlp.v2beta1.ContentItem items = 1;</code>
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * <pre>
     * The redacted content.
     * </pre>
     *
     * <code>repeated .google.privacy.dlp.v2beta1.ContentItem items = 1;</code>
     */
    public function setItems(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Privacy\Dlp\V2beta1\ContentItem::class);
        $this->items = $var;
    }

}

