<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/devtools/source/v1/source_context.proto

namespace Google\Devtools\Source\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * An alias to a repo revision.
 * </pre>
 *
 * Protobuf type <code>google.devtools.source.v1.AliasContext</code>
 */
class AliasContext extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The alias kind.
     * </pre>
     *
     * <code>.google.devtools.source.v1.AliasContext.Kind kind = 1;</code>
     */
    private $kind = 0;
    /**
     * <pre>
     * The alias name.
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    private $name = '';

    public function __construct() {
        \GPBMetadata\Google\Devtools\Source\V1\SourceContext::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The alias kind.
     * </pre>
     *
     * <code>.google.devtools.source.v1.AliasContext.Kind kind = 1;</code>
     */
    public function getKind()
    {
        return $this->kind;
    }

    /**
     * <pre>
     * The alias kind.
     * </pre>
     *
     * <code>.google.devtools.source.v1.AliasContext.Kind kind = 1;</code>
     */
    public function setKind($var)
    {
        GPBUtil::checkEnum($var, \Google\Devtools\Source\V1\AliasContext_Kind::class);
        $this->kind = $var;
    }

    /**
     * <pre>
     * The alias name.
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * <pre>
     * The alias name.
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

}

