<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/devtools/source/v1/source_context.proto

namespace Google\Devtools\Source\V1;

/**
 * <pre>
 * The type of an Alias.
 * </pre>
 *
 * Protobuf enum <code>google.devtools.source.v1.AliasContext.Kind</code>
 */
class AliasContext_Kind
{
    /**
     * <pre>
     * Do not use.
     * </pre>
     *
     * <code>ANY = 0;</code>
     */
    const ANY = 0;
    /**
     * <pre>
     * Git tag
     * </pre>
     *
     * <code>FIXED = 1;</code>
     */
    const FIXED = 1;
    /**
     * <pre>
     * Git branch
     * </pre>
     *
     * <code>MOVABLE = 2;</code>
     */
    const MOVABLE = 2;
    /**
     * <pre>
     * OTHER is used to specify non-standard aliases, those not of the kinds
     * above. For example, if a Git repo has a ref named "refs/foo/bar", it
     * is considered to be of kind OTHER.
     * </pre>
     *
     * <code>OTHER = 4;</code>
     */
    const OTHER = 4;
}

