<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/devtools/source/v1/source_context.proto

namespace Google\Devtools\Source\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * A SourceContext referring to a Gerrit project.
 * </pre>
 *
 * Protobuf type <code>google.devtools.source.v1.GerritSourceContext</code>
 */
class GerritSourceContext extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The URI of a running Gerrit instance.
     * </pre>
     *
     * <code>string host_uri = 1;</code>
     */
    private $host_uri = '';
    /**
     * <pre>
     * The full project name within the host. Projects may be nested, so
     * "project/subproject" is a valid project name.
     * The "repo name" is hostURI/project.
     * </pre>
     *
     * <code>string gerrit_project = 2;</code>
     */
    private $gerrit_project = '';
    protected $revision;

    public function __construct() {
        \GPBMetadata\Google\Devtools\Source\V1\SourceContext::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The URI of a running Gerrit instance.
     * </pre>
     *
     * <code>string host_uri = 1;</code>
     */
    public function getHostUri()
    {
        return $this->host_uri;
    }

    /**
     * <pre>
     * The URI of a running Gerrit instance.
     * </pre>
     *
     * <code>string host_uri = 1;</code>
     */
    public function setHostUri($var)
    {
        GPBUtil::checkString($var, True);
        $this->host_uri = $var;
    }

    /**
     * <pre>
     * The full project name within the host. Projects may be nested, so
     * "project/subproject" is a valid project name.
     * The "repo name" is hostURI/project.
     * </pre>
     *
     * <code>string gerrit_project = 2;</code>
     */
    public function getGerritProject()
    {
        return $this->gerrit_project;
    }

    /**
     * <pre>
     * The full project name within the host. Projects may be nested, so
     * "project/subproject" is a valid project name.
     * The "repo name" is hostURI/project.
     * </pre>
     *
     * <code>string gerrit_project = 2;</code>
     */
    public function setGerritProject($var)
    {
        GPBUtil::checkString($var, True);
        $this->gerrit_project = $var;
    }

    /**
     * <pre>
     * A revision (commit) ID.
     * </pre>
     *
     * <code>string revision_id = 3;</code>
     */
    public function getRevisionId()
    {
        return $this->readOneof(3);
    }

    /**
     * <pre>
     * A revision (commit) ID.
     * </pre>
     *
     * <code>string revision_id = 3;</code>
     */
    public function setRevisionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(3, $var);
    }

    /**
     * <pre>
     * The name of an alias (branch, tag, etc.).
     * </pre>
     *
     * <code>string alias_name = 4;</code>
     */
    public function getAliasName()
    {
        return $this->readOneof(4);
    }

    /**
     * <pre>
     * The name of an alias (branch, tag, etc.).
     * </pre>
     *
     * <code>string alias_name = 4;</code>
     */
    public function setAliasName($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(4, $var);
    }

    /**
     * <pre>
     * An alias, which may be a branch or tag.
     * </pre>
     *
     * <code>.google.devtools.source.v1.AliasContext alias_context = 5;</code>
     */
    public function getAliasContext()
    {
        return $this->readOneof(5);
    }

    /**
     * <pre>
     * An alias, which may be a branch or tag.
     * </pre>
     *
     * <code>.google.devtools.source.v1.AliasContext alias_context = 5;</code>
     */
    public function setAliasContext(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Devtools\Source\V1\AliasContext::class);
        $this->writeOneof(5, $var);
    }

    public function getRevision()
    {
        return $this->whichOneof("revision");
    }

}

