<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/functions/v1beta2/functions.proto

namespace Google\Cloud\Functions\V1beta2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Request for the `CreateFunction` method.
 * </pre>
 *
 * Protobuf type <code>google.cloud.functions.v1beta2.CreateFunctionRequest</code>
 */
class CreateFunctionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The project and location in which the function should be created, specified
     * in the format `projects/&#42;&#47;locations/&#42;`
     * </pre>
     *
     * <code>string location = 1;</code>
     */
    private $location = '';
    /**
     * <pre>
     * Function to be created.
     * </pre>
     *
     * <code>.google.cloud.functions.v1beta2.CloudFunction function = 2;</code>
     */
    private $function = null;

    public function __construct() {
        \GPBMetadata\Google\Cloud\Functions\V1Beta2\Functions::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The project and location in which the function should be created, specified
     * in the format `projects/&#42;&#47;locations/&#42;`
     * </pre>
     *
     * <code>string location = 1;</code>
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * <pre>
     * The project and location in which the function should be created, specified
     * in the format `projects/&#42;&#47;locations/&#42;`
     * </pre>
     *
     * <code>string location = 1;</code>
     */
    public function setLocation($var)
    {
        GPBUtil::checkString($var, True);
        $this->location = $var;
    }

    /**
     * <pre>
     * Function to be created.
     * </pre>
     *
     * <code>.google.cloud.functions.v1beta2.CloudFunction function = 2;</code>
     */
    public function getFunction()
    {
        return $this->function;
    }

    /**
     * <pre>
     * Function to be created.
     * </pre>
     *
     * <code>.google.cloud.functions.v1beta2.CloudFunction function = 2;</code>
     */
    public function setFunction(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Cloud\Functions\V1beta2\CloudFunction::class);
        $this->function = $var;
    }

}

