<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/functions/v1beta2/operations.proto

namespace Google\Cloud\Functions\V1beta2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Metadata describing an [Operation][google.longrunning.Operation]
 * </pre>
 *
 * Protobuf type <code>google.cloud.functions.v1beta2.OperationMetadataV1Beta2</code>
 */
class OperationMetadataV1Beta2 extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * Target of the operation - for example
     * projects/project-1/locations/region-1/functions/function-1
     * </pre>
     *
     * <code>string target = 1;</code>
     */
    private $target = '';
    /**
     * <pre>
     * Type of operation.
     * </pre>
     *
     * <code>.google.cloud.functions.v1beta2.OperationType type = 2;</code>
     */
    private $type = 0;
    /**
     * <pre>
     * The original request that started the operation.
     * </pre>
     *
     * <code>.google.protobuf.Any request = 3;</code>
     */
    private $request = null;

    public function __construct() {
        \GPBMetadata\Google\Cloud\Functions\V1Beta2\Operations::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Target of the operation - for example
     * projects/project-1/locations/region-1/functions/function-1
     * </pre>
     *
     * <code>string target = 1;</code>
     */
    public function getTarget()
    {
        return $this->target;
    }

    /**
     * <pre>
     * Target of the operation - for example
     * projects/project-1/locations/region-1/functions/function-1
     * </pre>
     *
     * <code>string target = 1;</code>
     */
    public function setTarget($var)
    {
        GPBUtil::checkString($var, True);
        $this->target = $var;
    }

    /**
     * <pre>
     * Type of operation.
     * </pre>
     *
     * <code>.google.cloud.functions.v1beta2.OperationType type = 2;</code>
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * <pre>
     * Type of operation.
     * </pre>
     *
     * <code>.google.cloud.functions.v1beta2.OperationType type = 2;</code>
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Google\Cloud\Functions\V1beta2\OperationType::class);
        $this->type = $var;
    }

    /**
     * <pre>
     * The original request that started the operation.
     * </pre>
     *
     * <code>.google.protobuf.Any request = 3;</code>
     */
    public function getRequest()
    {
        return $this->request;
    }

    /**
     * <pre>
     * The original request that started the operation.
     * </pre>
     *
     * <code>.google.protobuf.Any request = 3;</code>
     */
    public function setRequest(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Any::class);
        $this->request = $var;
    }

}

