<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/functions/v1beta2/functions.proto

namespace Google\Cloud\Functions\V1beta2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Request for the `UpdateFunction` method.
 * </pre>
 *
 * Protobuf type <code>google.cloud.functions.v1beta2.UpdateFunctionRequest</code>
 */
class UpdateFunctionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The name of the function to be updated.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    private $name = '';
    /**
     * <pre>
     * New version of the function.
     * </pre>
     *
     * <code>.google.cloud.functions.v1beta2.CloudFunction function = 2;</code>
     */
    private $function = null;

    public function __construct() {
        \GPBMetadata\Google\Cloud\Functions\V1Beta2\Functions::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The name of the function to be updated.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * <pre>
     * The name of the function to be updated.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

    /**
     * <pre>
     * New version of the function.
     * </pre>
     *
     * <code>.google.cloud.functions.v1beta2.CloudFunction function = 2;</code>
     */
    public function getFunction()
    {
        return $this->function;
    }

    /**
     * <pre>
     * New version of the function.
     * </pre>
     *
     * <code>.google.cloud.functions.v1beta2.CloudFunction function = 2;</code>
     */
    public function setFunction(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Cloud\Functions\V1beta2\CloudFunction::class);
        $this->function = $var;
    }

}

