<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/type/color.proto

namespace Google\Type;

require_once('google/protobuf/wrappers.pb.php');
use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class Color extends \Google\Protobuf\Internal\Message
{
    private $red = 0.0;
    private $green = 0.0;
    private $blue = 0.0;
    private $alpha = null;

    public function getRed()
    {
        return $this->red;
    }

    public function setRed($var)
    {
        GPBUtil::checkFloat($var);
        $this->red = $var;
    }

    public function getGreen()
    {
        return $this->green;
    }

    public function setGreen($var)
    {
        GPBUtil::checkFloat($var);
        $this->green = $var;
    }

    public function getBlue()
    {
        return $this->blue;
    }

    public function setBlue($var)
    {
        GPBUtil::checkFloat($var);
        $this->blue = $var;
    }

    public function getAlpha()
    {
        return $this->alpha;
    }

    public function setAlpha(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\FloatValue::class);
        $this->alpha = $var;
    }

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0ad4010a17676f6f676c652f747970652f636f6c6f722e70726f746f120b" .
    "676f6f676c652e747970651a1e676f6f676c652f70726f746f6275662f77" .
    "726170706572732e70726f746f225d0a05436f6c6f72120b0a0372656418" .
    "0120012802120d0a05677265656e180220012802120c0a04626c75651803" .
    "20012802122a0a05616c70686118042001280b321b2e676f6f676c652e70" .
    "726f746f6275662e466c6f617456616c756542250a0f636f6d2e676f6f67" .
    "6c652e74797065420a436f6c6f7250726f746f5001a20203475450620670" .
    "726f746f33"
));

