<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/type/timeofday.proto

namespace Google\Type;

use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class TimeOfDay extends \Google\Protobuf\Internal\Message
{
    private $hours = 0;
    private $minutes = 0;
    private $seconds = 0;
    private $nanos = 0;

    public function getHours()
    {
        return $this->hours;
    }

    public function setHours($var)
    {
        GPBUtil::checkInt32($var);
        $this->hours = $var;
    }

    public function getMinutes()
    {
        return $this->minutes;
    }

    public function setMinutes($var)
    {
        GPBUtil::checkInt32($var);
        $this->minutes = $var;
    }

    public function getSeconds()
    {
        return $this->seconds;
    }

    public function setSeconds($var)
    {
        GPBUtil::checkInt32($var);
        $this->seconds = $var;
    }

    public function getNanos()
    {
        return $this->nanos;
    }

    public function setNanos($var)
    {
        GPBUtil::checkInt32($var);
        $this->nanos = $var;
    }

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0aaa010a1b676f6f676c652f747970652f74696d656f666461792e70726f" .
    "746f120b676f6f676c652e74797065224b0a0954696d654f66446179120d" .
    "0a05686f757273180120012805120f0a076d696e75746573180220012805" .
    "120f0a077365636f6e6473180320012805120d0a056e616e6f7318042001" .
    "280542290a0f636f6d2e676f6f676c652e74797065420e54696d654f6644" .
    "617950726f746f5001a20203475450620670726f746f33"
));

