<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/datastore/v1/datastore.proto

namespace Google\Datastore\V1;

/**
 * <pre>
 * The modes available for commits.
 * </pre>
 *
 * Protobuf enum <code>google.datastore.v1.CommitRequest.Mode</code>
 */
class CommitRequest_Mode
{
    /**
     * <pre>
     * Unspecified. This value must not be used.
     * </pre>
     *
     * <code>MODE_UNSPECIFIED = 0;</code>
     */
    const MODE_UNSPECIFIED = 0;
    /**
     * <pre>
     * Transactional: The mutations are either all applied, or none are applied.
     * Learn about transactions [here](https://cloud.google.com/datastore/docs/concepts/transactions).
     * </pre>
     *
     * <code>TRANSACTIONAL = 1;</code>
     */
    const TRANSACTIONAL = 1;
    /**
     * <pre>
     * Non-transactional: The mutations may not apply as all or none.
     * </pre>
     *
     * <code>NON_TRANSACTIONAL = 2;</code>
     */
    const NON_TRANSACTIONAL = 2;
}

