<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/datastore/v1/query.proto

namespace Google\Datastore\V1;

/**
 * <pre>
 * Specifies what data the 'entity' field contains.
 * A `ResultType` is either implied (for example, in `LookupResponse.missing`
 * from `datastore.proto`, it is always `KEY_ONLY`) or specified by context
 * (for example, in message `QueryResultBatch`, field `entity_result_type`
 * specifies a `ResultType` for all the values in field `entity_results`).
 * </pre>
 *
 * Protobuf enum <code>google.datastore.v1.EntityResult.ResultType</code>
 */
class EntityResult_ResultType
{
    /**
     * <pre>
     * Unspecified. This value is never used.
     * </pre>
     *
     * <code>RESULT_TYPE_UNSPECIFIED = 0;</code>
     */
    const RESULT_TYPE_UNSPECIFIED = 0;
    /**
     * <pre>
     * The key and properties.
     * </pre>
     *
     * <code>FULL = 1;</code>
     */
    const FULL = 1;
    /**
     * <pre>
     * A projected subset of properties. The entity may have no key.
     * </pre>
     *
     * <code>PROJECTION = 2;</code>
     */
    const PROJECTION = 2;
    /**
     * <pre>
     * Only the key.
     * </pre>
     *
     * <code>KEY_ONLY = 3;</code>
     */
    const KEY_ONLY = 3;
}

