<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/datastore/v1/entity.proto

namespace Google\Datastore\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * A partition ID identifies a grouping of entities. The grouping is always
 * by project and namespace, however the namespace ID may be empty.
 * A partition ID contains several dimensions:
 * project ID and namespace ID.
 * Partition dimensions:
 * - May be `""`.
 * - Must be valid UTF-8 bytes.
 * - Must have values that match regex `[A-Za-z&#92;d&#92;.&#92;-_]{1,100}`
 * If the value of any dimension matches regex `__.*__`, the partition is
 * reserved/read-only.
 * A reserved/read-only partition ID is forbidden in certain documented
 * contexts.
 * Foreign partition IDs (in which the project ID does
 * not match the context project ID ) are discouraged.
 * Reads and writes of foreign partition IDs may fail if the project is not in an active state.
 * </pre>
 *
 * Protobuf type <code>google.datastore.v1.PartitionId</code>
 */
class PartitionId extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The ID of the project to which the entities belong.
     * </pre>
     *
     * <code>string project_id = 2;</code>
     */
    private $project_id = '';
    /**
     * <pre>
     * If not empty, the ID of the namespace to which the entities belong.
     * </pre>
     *
     * <code>string namespace_id = 4;</code>
     */
    private $namespace_id = '';

    public function __construct() {
        \GPBMetadata\Google\Datastore\V1\Entity::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The ID of the project to which the entities belong.
     * </pre>
     *
     * <code>string project_id = 2;</code>
     */
    public function getProjectId()
    {
        return $this->project_id;
    }

    /**
     * <pre>
     * The ID of the project to which the entities belong.
     * </pre>
     *
     * <code>string project_id = 2;</code>
     */
    public function setProjectId($var)
    {
        GPBUtil::checkString($var, True);
        $this->project_id = $var;
    }

    /**
     * <pre>
     * If not empty, the ID of the namespace to which the entities belong.
     * </pre>
     *
     * <code>string namespace_id = 4;</code>
     */
    public function getNamespaceId()
    {
        return $this->namespace_id;
    }

    /**
     * <pre>
     * If not empty, the ID of the namespace to which the entities belong.
     * </pre>
     *
     * <code>string namespace_id = 4;</code>
     */
    public function setNamespaceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->namespace_id = $var;
    }

}

