<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/datastore/v1/query.proto

namespace Google\Datastore\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * The desired order for a specific property.
 * </pre>
 *
 * Protobuf type <code>google.datastore.v1.PropertyOrder</code>
 */
class PropertyOrder extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The property to order by.
     * </pre>
     *
     * <code>.google.datastore.v1.PropertyReference property = 1;</code>
     */
    private $property = null;
    /**
     * <pre>
     * The direction to order by. Defaults to `ASCENDING`.
     * </pre>
     *
     * <code>.google.datastore.v1.PropertyOrder.Direction direction = 2;</code>
     */
    private $direction = 0;

    public function __construct() {
        \GPBMetadata\Google\Datastore\V1\Query::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The property to order by.
     * </pre>
     *
     * <code>.google.datastore.v1.PropertyReference property = 1;</code>
     */
    public function getProperty()
    {
        return $this->property;
    }

    /**
     * <pre>
     * The property to order by.
     * </pre>
     *
     * <code>.google.datastore.v1.PropertyReference property = 1;</code>
     */
    public function setProperty(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Datastore\V1\PropertyReference::class);
        $this->property = $var;
    }

    /**
     * <pre>
     * The direction to order by. Defaults to `ASCENDING`.
     * </pre>
     *
     * <code>.google.datastore.v1.PropertyOrder.Direction direction = 2;</code>
     */
    public function getDirection()
    {
        return $this->direction;
    }

    /**
     * <pre>
     * The direction to order by. Defaults to `ASCENDING`.
     * </pre>
     *
     * <code>.google.datastore.v1.PropertyOrder.Direction direction = 2;</code>
     */
    public function setDirection($var)
    {
        GPBUtil::checkEnum($var, \Google\Datastore\V1\PropertyOrder_Direction::class);
        $this->direction = $var;
    }

}

