<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/datastore/v1/datastore.proto

namespace Google\Datastore\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * The response for [Datastore.Rollback][google.datastore.v1.Datastore.Rollback].
 * (an empty message).
 * </pre>
 *
 * Protobuf type <code>google.datastore.v1.RollbackResponse</code>
 */
class RollbackResponse extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Google\Datastore\V1\Datastore::initOnce();
        parent::__construct();
    }

}

