<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/logging/type/log_severity.proto

namespace Google\Logging\Type;

require_once('google/api/annotations.pb.php');
use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class LogSeverity
{
    const DEFAULTO = 0;
    const DEBUG = 100;
    const INFO = 200;
    const NOTICE = 300;
    const WARNING = 400;
    const ERROR = 500;
    const CRITICAL = 600;
    const ALERT = 700;
    const EMERGENCY = 800;
}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0a97020a26676f6f676c652f6c6f6767696e672f747970652f6c6f675f73" .
    "657665726974792e70726f746f1213676f6f676c652e6c6f6767696e672e" .
    "747970651a1c676f6f676c652f6170692f616e6e6f746174696f6e732e70" .
    "726f746f2a82010a0b4c6f675365766572697479120b0a0744454641554c" .
    "54100012090a054445425547106412090a04494e464f10c801120b0a064e" .
    "4f5449434510ac02120c0a075741524e494e47109003120a0a054552524f" .
    "5210f403120d0a08435249544943414c10d804120a0a05414c45525410bc" .
    "05120e0a09454d455247454e435910a006422d0a17636f6d2e676f6f676c" .
    "652e6c6f6767696e672e7479706542104c6f67536576657269747950726f" .
    "746f5001620670726f746f33"
));

