<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/logging/v2/log_entry.proto

namespace Google\Logging\V2;

require_once('google/api/annotations.pb.php');
require_once('google/api/monitored_resource.pb.php');
require_once('google/logging/type/http_request.pb.php');
require_once('google/logging/type/log_severity.pb.php');
require_once('google/protobuf/any.pb.php');
require_once('google/protobuf/struct.pb.php');
require_once('google/protobuf/timestamp.pb.php');
use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class LogEntry extends \Google\Protobuf\Internal\Message
{
    private $log_name = '';
    private $resource = null;
    private $timestamp = null;
    private $severity = 0;
    private $insert_id = '';
    private $http_request = null;
    private $labels;
    private $operation = null;
    protected $payload;

    public function getLogName()
    {
        return $this->log_name;
    }

    public function setLogName($var)
    {
        GPBUtil::checkString($var, True);
        $this->log_name = $var;
    }

    public function getResource()
    {
        return $this->resource;
    }

    public function setResource(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Api\MonitoredResource::class);
        $this->resource = $var;
    }

    public function getProtoPayload()
    {
        return $this->readOneof(2);
    }

    public function setProtoPayload(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Any::class);
        $this->writeOneof(2, $var);
    }

    public function getTextPayload()
    {
        return $this->readOneof(3);
    }

    public function setTextPayload($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(3, $var);
    }

    public function getJsonPayload()
    {
        return $this->readOneof(6);
    }

    public function setJsonPayload(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->writeOneof(6, $var);
    }

    public function getTimestamp()
    {
        return $this->timestamp;
    }

    public function setTimestamp(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->timestamp = $var;
    }

    public function getSeverity()
    {
        return $this->severity;
    }

    public function setSeverity($var)
    {
        GPBUtil::checkEnum($var, \Google\Logging\Type\LogSeverity::class);
        $this->severity = $var;
    }

    public function getInsertId()
    {
        return $this->insert_id;
    }

    public function setInsertId($var)
    {
        GPBUtil::checkString($var, True);
        $this->insert_id = $var;
    }

    public function getHttpRequest()
    {
        return $this->http_request;
    }

    public function setHttpRequest(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Logging\Type\HttpRequest::class);
        $this->http_request = $var;
    }

    public function getLabels()
    {
        return $this->labels;
    }

    public function setLabels(&$var)
    {
        $this->labels = $var;
    }

    public function getOperation()
    {
        return $this->operation;
    }

    public function setOperation(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Logging\V2\LogEntryOperation::class);
        $this->operation = $var;
    }

    public function getPayload()
    {
        return $this->payload;
    }

}

class LogEntryOperation extends \Google\Protobuf\Internal\Message
{
    private $id = '';
    private $producer = '';
    private $first = false;
    private $last = false;

    public function getId()
    {
        return $this->id;
    }

    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;
    }

    public function getProducer()
    {
        return $this->producer;
    }

    public function setProducer($var)
    {
        GPBUtil::checkString($var, True);
        $this->producer = $var;
    }

    public function getFirst()
    {
        return $this->first;
    }

    public function setFirst($var)
    {
        GPBUtil::checkBool($var);
        $this->first = $var;
    }

    public function getLast()
    {
        return $this->last;
    }

    public function setLast($var)
    {
        GPBUtil::checkBool($var);
        $this->last = $var;
    }

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0afc070a21676f6f676c652f6c6f6767696e672f76322f6c6f675f656e74" .
    "72792e70726f746f1211676f6f676c652e6c6f6767696e672e76321a1c67" .
    "6f6f676c652f6170692f616e6e6f746174696f6e732e70726f746f1a2367" .
    "6f6f676c652f6170692f6d6f6e69746f7265645f7265736f757263652e70" .
    "726f746f1a26676f6f676c652f6c6f6767696e672f747970652f68747470" .
    "5f726571756573742e70726f746f1a26676f6f676c652f6c6f6767696e67" .
    "2f747970652f6c6f675f73657665726974792e70726f746f1a19676f6f67" .
    "6c652f70726f746f6275662f616e792e70726f746f1a1c676f6f676c652f" .
    "70726f746f6275662f7374727563742e70726f746f1a1f676f6f676c652f" .
    "70726f746f6275662f74696d657374616d702e70726f746f229f040a084c" .
    "6f67456e74727912100a086c6f675f6e616d65180c20012809122f0a0872" .
    "65736f7572636518082001280b321d2e676f6f676c652e6170692e4d6f6e" .
    "69746f7265645265736f75726365122d0a0d70726f746f5f7061796c6f61" .
    "6418022001280b32142e676f6f676c652e70726f746f6275662e416e7948" .
    "0012160a0c746578745f7061796c6f61641803200128094800122f0a0c6a" .
    "736f6e5f7061796c6f616418062001280b32172e676f6f676c652e70726f" .
    "746f6275662e5374727563744800122d0a0974696d657374616d70180920" .
    "01280b321a2e676f6f676c652e70726f746f6275662e54696d657374616d" .
    "7012320a087365766572697479180a2001280e32202e676f6f676c652e6c" .
    "6f6767696e672e747970652e4c6f67536576657269747912110a09696e73" .
    "6572745f696418042001280912360a0c687474705f726571756573741807" .
    "2001280b32202e676f6f676c652e6c6f6767696e672e747970652e487474" .
    "705265717565737412370a066c6162656c73180b2003280b32272e676f6f" .
    "676c652e6c6f6767696e672e76322e4c6f67456e7472792e4c6162656c73" .
    "456e74727912370a096f7065726174696f6e180f2001280b32242e676f6f" .
    "676c652e6c6f6767696e672e76322e4c6f67456e7472794f706572617469" .
    "6f6e1a2d0a0b4c6162656c73456e747279120b0a036b6579180120012809" .
    "120d0a0576616c75651802200128093a02380142090a077061796c6f6164" .
    "224e0a114c6f67456e7472794f7065726174696f6e120a0a026964180120" .
    "01280912100a0870726f6475636572180220012809120d0a056669727374" .
    "180320012808120c0a046c617374180420012808425d0a15636f6d2e676f" .
    "6f676c652e6c6f6767696e672e7632420d4c6f67456e74727950726f746f" .
    "50015a30676f6f676c652e676f6c616e672e6f72672f67656e70726f746f" .
    "2f676f6f676c65617069732f6c6f6767696e672f7632f80101620670726f" .
    "746f33"
));

