<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/logging/v2/logging.proto

namespace Google\Logging\V2;

require_once('google/api/annotations.pb.php');
require_once('google/api/monitored_resource.pb.php');
require_once('google/logging/v2/log_entry.pb.php');
require_once('google/protobuf/duration.pb.php');
require_once('google/protobuf/empty.pb.php');
require_once('google/protobuf/timestamp.pb.php');
require_once('google/rpc/status.pb.php');
use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class DeleteLogRequest extends \Google\Protobuf\Internal\Message
{
    private $log_name = '';

    public function getLogName()
    {
        return $this->log_name;
    }

    public function setLogName($var)
    {
        GPBUtil::checkString($var, True);
        $this->log_name = $var;
    }

}

class WriteLogEntriesRequest extends \Google\Protobuf\Internal\Message
{
    private $log_name = '';
    private $resource = null;
    private $labels;
    private $entries;
    private $partial_success = false;

    public function getLogName()
    {
        return $this->log_name;
    }

    public function setLogName($var)
    {
        GPBUtil::checkString($var, True);
        $this->log_name = $var;
    }

    public function getResource()
    {
        return $this->resource;
    }

    public function setResource(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Api\MonitoredResource::class);
        $this->resource = $var;
    }

    public function getLabels()
    {
        return $this->labels;
    }

    public function setLabels(&$var)
    {
        $this->labels = $var;
    }

    public function getEntries()
    {
        return $this->entries;
    }

    public function setEntries(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Google\Logging\V2\LogEntry::class);
        $this->entries = $var;
    }

    public function getPartialSuccess()
    {
        return $this->partial_success;
    }

    public function setPartialSuccess($var)
    {
        GPBUtil::checkBool($var);
        $this->partial_success = $var;
    }

}

class WriteLogEntriesResponse extends \Google\Protobuf\Internal\Message
{

}

class ListLogEntriesRequest extends \Google\Protobuf\Internal\Message
{
    private $project_ids;
    private $resource_names;
    private $filter = '';
    private $order_by = '';
    private $page_size = 0;
    private $page_token = '';

    public function getProjectIds()
    {
        return $this->project_ids;
    }

    public function setProjectIds(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::STRING);
        $this->project_ids = $var;
    }

    public function getResourceNames()
    {
        return $this->resource_names;
    }

    public function setResourceNames(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::STRING);
        $this->resource_names = $var;
    }

    public function getFilter()
    {
        return $this->filter;
    }

    public function setFilter($var)
    {
        GPBUtil::checkString($var, True);
        $this->filter = $var;
    }

    public function getOrderBy()
    {
        return $this->order_by;
    }

    public function setOrderBy($var)
    {
        GPBUtil::checkString($var, True);
        $this->order_by = $var;
    }

    public function getPageSize()
    {
        return $this->page_size;
    }

    public function setPageSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->page_size = $var;
    }

    public function getPageToken()
    {
        return $this->page_token;
    }

    public function setPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->page_token = $var;
    }

}

class ListLogEntriesResponse extends \Google\Protobuf\Internal\Message
{
    private $entries;
    private $next_page_token = '';

    public function getEntries()
    {
        return $this->entries;
    }

    public function setEntries(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Google\Logging\V2\LogEntry::class);
        $this->entries = $var;
    }

    public function getNextPageToken()
    {
        return $this->next_page_token;
    }

    public function setNextPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->next_page_token = $var;
    }

}

class ListMonitoredResourceDescriptorsRequest extends \Google\Protobuf\Internal\Message
{
    private $page_size = 0;
    private $page_token = '';

    public function getPageSize()
    {
        return $this->page_size;
    }

    public function setPageSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->page_size = $var;
    }

    public function getPageToken()
    {
        return $this->page_token;
    }

    public function setPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->page_token = $var;
    }

}

class ListMonitoredResourceDescriptorsResponse extends \Google\Protobuf\Internal\Message
{
    private $resource_descriptors;
    private $next_page_token = '';

    public function getResourceDescriptors()
    {
        return $this->resource_descriptors;
    }

    public function setResourceDescriptors(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Google\Api\MonitoredResourceDescriptor::class);
        $this->resource_descriptors = $var;
    }

    public function getNextPageToken()
    {
        return $this->next_page_token;
    }

    public function setNextPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->next_page_token = $var;
    }

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0a870e0a1f676f6f676c652f6c6f6767696e672f76322f6c6f6767696e67" .
    "2e70726f746f1211676f6f676c652e6c6f6767696e672e76321a1c676f6f" .
    "676c652f6170692f616e6e6f746174696f6e732e70726f746f1a23676f6f" .
    "676c652f6170692f6d6f6e69746f7265645f7265736f757263652e70726f" .
    "746f1a21676f6f676c652f6c6f6767696e672f76322f6c6f675f656e7472" .
    "792e70726f746f1a1e676f6f676c652f70726f746f6275662f6475726174" .
    "696f6e2e70726f746f1a1b676f6f676c652f70726f746f6275662f656d70" .
    "74792e70726f746f1a1f676f6f676c652f70726f746f6275662f74696d65" .
    "7374616d702e70726f746f1a17676f6f676c652f7270632f737461747573" .
    "2e70726f746f22240a1044656c6574654c6f675265717565737412100a08" .
    "6c6f675f6e616d651801200128092298020a1657726974654c6f67456e74" .
    "726965735265717565737412100a086c6f675f6e616d6518012001280912" .
    "2f0a087265736f7572636518022001280b321d2e676f6f676c652e617069" .
    "2e4d6f6e69746f7265645265736f7572636512450a066c6162656c731803" .
    "2003280b32352e676f6f676c652e6c6f6767696e672e76322e5772697465" .
    "4c6f67456e7472696573526571756573742e4c6162656c73456e74727912" .
    "2c0a07656e747269657318042003280b321b2e676f6f676c652e6c6f6767" .
    "696e672e76322e4c6f67456e74727912170a0f7061727469616c5f737563" .
    "636573731805200128081a2d0a0b4c6162656c73456e747279120b0a036b" .
    "6579180120012809120d0a0576616c75651802200128093a02380122190a" .
    "1757726974654c6f67456e7472696573526573706f6e7365228d010a154c" .
    "6973744c6f67456e74726965735265717565737412130a0b70726f6a6563" .
    "745f69647318012003280912160a0e7265736f757263655f6e616d657318" .
    "0820032809120e0a0666696c74657218022001280912100a086f72646572" .
    "5f627918032001280912110a09706167655f73697a651804200128051212" .
    "0a0a706167655f746f6b656e180520012809225f0a164c6973744c6f6745" .
    "6e7472696573526573706f6e7365122c0a07656e74726965731801200328" .
    "0b321b2e676f6f676c652e6c6f6767696e672e76322e4c6f67456e747279" .
    "12170a0f6e6578745f706167655f746f6b656e18022001280922500a274c" .
    "6973744d6f6e69746f7265645265736f7572636544657363726970746f72" .
    "735265717565737412110a09706167655f73697a6518012001280512120a" .
    "0a706167655f746f6b656e180220012809228a010a284c6973744d6f6e69" .
    "746f7265645265736f7572636544657363726970746f7273526573706f6e" .
    "736512450a147265736f757263655f64657363726970746f727318012003" .
    "280b32272e676f6f676c652e6170692e4d6f6e69746f7265645265736f75" .
    "72636544657363726970746f7212170a0f6e6578745f706167655f746f6b" .
    "656e18022001280932e1040a104c6f6767696e6753657276696365563212" .
    "770a0944656c6574654c6f6712232e676f6f676c652e6c6f6767696e672e" .
    "76322e44656c6574654c6f67526571756573741a162e676f6f676c652e70" .
    "726f746f6275662e456d707479222d82d3e49302272a252f763262657461" .
    "312f7b6c6f675f6e616d653d70726f6a656374732f2a2f6c6f67732f2a7d" .
    "1286010a0f57726974654c6f67456e747269657312292e676f6f676c652e" .
    "6c6f6767696e672e76322e57726974654c6f67456e747269657352657175" .
    "6573741a2a2e676f6f676c652e6c6f6767696e672e76322e57726974654c" .
    "6f67456e7472696573526573706f6e7365221c82d3e493021622112f7632" .
    "2f656e74726965733a77726974653a012a1282010a0e4c6973744c6f6745" .
    "6e747269657312282e676f6f676c652e6c6f6767696e672e76322e4c6973" .
    "744c6f67456e7472696573526571756573741a292e676f6f676c652e6c6f" .
    "6767696e672e76322e4c6973744c6f67456e7472696573526573706f6e73" .
    "65221b82d3e493021522102f76322f656e74726965733a6c6973743a012a" .
    "12c5010a204c6973744d6f6e69746f7265645265736f7572636544657363" .
    "726970746f7273123a2e676f6f676c652e6c6f6767696e672e76322e4c69" .
    "73744d6f6e69746f7265645265736f7572636544657363726970746f7273" .
    "526571756573741a3b2e676f6f676c652e6c6f6767696e672e76322e4c69" .
    "73744d6f6e69746f7265645265736f7572636544657363726970746f7273" .
    "526573706f6e7365222882d3e493022212202f76322f6d6f6e69746f7265" .
    "645265736f7572636544657363726970746f7273425c0a15636f6d2e676f" .
    "6f676c652e6c6f6767696e672e7632420c4c6f6767696e6750726f746f50" .
    "015a30676f6f676c652e676f6c616e672e6f72672f67656e70726f746f2f" .
    "676f6f676c65617069732f6c6f6767696e672f7632f80101620670726f74" .
    "6f33"
));

